### ISSUE TITLE
ngrok setup

### ISSUE THREAD

**Issue by Tevalo** [karma9874/AndroRAT#103]
Hi,

I am experimenting a bit with ngrok and everything works fine for me when building the apk with following line:
python androRAT.py --build --ngrok -o rat.apk

As soon as the apk is build the shell interface is opened automatically and when I install the app on my phone it works flawlessly.

However, when I close the console, the ngrok tunnel gets closed and I cannot establish the connection again. I tried a few combinations for example opening the tunnel with the port it gives me when building the app or that was shown in my ngrok connections. I also searched the internet but nothing worked. I figured out, that the forwarding address e.g. tcp://6.tcp.ngrok.io:14682 is always different. Can some kind and noble soul may help me on this problem?

Thanks in advance!

**Comment by karma9874** [comment]
Hey,
Actually here you are using ngrok free version so in the free version the TCP address is not reserved it means it will change every time when you run ngrok
So to have a permanent connection 2 things can be done 
1. Use ngrok premium which will give you a reserved TCP address
2. Do port forwarding on your ISP so you can have a permanent connection.

**Comment by swagkarna** [comment]
@Tevalo use portmap.io for stable and free port forwarding if u dont wanna get trouble in port forwarding u can use this rat this rat does not require port forwarding
https://github.com/swagkarna/Rafel-Rat

**Comment by anandanandafer** [comment]
thanks for all, but i want asking how using ngrok and androRAT, please tutorial full , thank you, good bless you all
