### ISSUE TITLE
python traceback (most recent call last) 

### ISSUE THREAD

**Issue by HACKERgan** [karma9874/AndroRAT#106]
![IMG_20211122_133613_173](https://user-images.githubusercontent.com/94834014/142839796-6b21f59f-ba1a-44b3-a41f-92269da5ea1e.jpg)
Please solve this problem 🙏

**Comment by HACKERgan** [comment]
Please help me bro

**Comment by Dexter-lala** [comment]
> Please help me bro

go with python3 instead of just python

**Comment by nickfour** [comment]
> > Please help me bro
> 
> go with python3 instead of just python

![Uploading Screenshot_2022-11-17-21-55-32-08_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by nickfour** [comment]
> > Please help me bro
> 
> go with python3 instead of just python

Not working
