### ISSUE TITLE
sign problem

### ISSUE THREAD

**Issue by WHITE-HAT786** [karma9874/AndroRAT#108]
<a href="https://imgur.com/VHNZNHx.png">
  <img src="https://imgur.com/VHNZNHx.png" />
</a>
help please

**Comment by lazengann86** [comment]
Same issue here. Anyone for a way around it?

**Comment by HenyPotter** [comment]
Same issue here! I don't know where is the problem :/

**Comment by The3Hat** [comment]
> [ ![](https://camo.githubusercontent.com/4ad6e658adb7de41f09b71ec07688cf1ffd7f884ef6fff6609a1b8fdd8476c41/68747470733a2f2f696d6775722e636f6d2f56484e5a4e48782e706e67) ](https://imgur.com/VHNZNHx.png) help please

Use openjdk-8-jdk

**Comment by The3Hat** [comment]
i mean u must have java version 8 instead of 11

**Comment by karma9874** [comment]
duplicate of #119

**Comment by WHITE-HAT786** [comment]
My issue solved
 I changed by Java version
