### ISSUE TITLE
Cant run on termux

### ISSUE THREAD

**Issue by Sabbir589** [karma9874/AndroRAT#113]
**I cant run it on my termux**
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 52, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 370, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by drunkm3m3r** [comment]
I'm getting this error too, but on windows 11. Any fix? @Sabbir589

**Comment by G4lixou** [comment]
Same error

**Comment by TarunChakitha** [comment]
> **I cant run it on my termux** Traceback (most recent call last): File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 52, in build(args.ip,port_,args.output,False,None,icon) File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 370, in build version_no = re.search(pattern, java_version.stderr).groups()[0] AttributeError: 'NoneType' object has no attribute 'groups'

Install Java SE 8 on your machine (and set the environment variables if using windows)

`version_no = re.search(pattern, java_version.stderr).groups()[0]
`
The above line searches for java version number installed on your machine.

**Comment by abekuchbhi** [comment]
> 

An how to install Java se8 in termux??

**Comment by abekuchbhi** [comment]
Error 🤕
python3 androRAT.py --build -i 100.88.168.60 -p 4444 -o info.apk
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 52, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 370, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
$

**Comment by TarunChakitha** [comment]
> > 
> 
> An how to install Java se8 in termux??

I haven't tested it completely but...
1. Installed java 8 from here - [](https://github.com/MasterDevX/Termux-Java)
2. Had an error `Bad system call` on running `java -version` so I followed [this comment](https://github.com/MasterDevX/Termux-Java/issues/39#issuecomment-761841767) to fix it

Used it with python3.10 and it successfully built and signed the apk.

**Comment by abekuchbhi** [comment]
>gorom where u installed???

**Comment by TarunChakitha** [comment]
> From where u installed???
From here https://github.com/MasterDevX/Termux-Java
