### ISSUE TITLE
connection back

### ISSUE THREAD

**Issue by NBamol** [karma9874/AndroRAT#114]
How can i get the connection back after i exited the first connection because when i run python command again it says [ERROR]  [Errno 98] Address already in use
![Capture1](https://user-images.githubusercontent.com/79451013/148349603-1651950a-860e-474e-baf6-82f0442c4036.PNG)

**Comment by hakai45** [comment]
Be sure to exit the session before closing the terminal/session

**Comment by hakai45** [comment]
otherwise he will use that forever until removed

**Comment by Marcioshub** [comment]
I added a one line of code that fixes this, hopefully it gets accepted.
