### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by santoshdawre** [karma9874/AndroRAT#117]
┌──(root💀kali)-[~/Desktop/AndroRAT]
└─# python3 androRAT.py -h                                  
Traceback (most recent call last):
  File "/root/Desktop/AndroRAT/androRAT.py", line 4, in <module>
    from utils import *
  File "/root/Desktop/AndroRAT/utils.py", line 14, in <module>
    from colorama import Fore, Style,init
ModuleNotFoundError: No module named 'colorama'

┌──(root💀kali)-[~/Desktop/AndroRAT]
└─# pip install -r requirements.txt
Requirement already satisfied: **colorama_** in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (0.4.4)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (5.1.0)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyngrok->-r requirements.txt (line 2)) (5.4.1)
****

please help for this error,thanks in advance

**Comment by shuence** [comment]
Try uninstalling colorama by `pip uninstall colorama` &&
Installing it again by `pip install colorama`
Hope this will work .....!

**Comment by mohithreddy12** [comment]
pip uninstall colorama not working
error :- uninstall command not found

**Comment by shuence** [comment]
`pip uninstall <packagename>`
try this

**Comment by mohithreddy12** [comment]
![IMG20220215070459](https://user-images.githubusercontent.com/73573077/153976246-e70ac1b4-132d-4cde-97b0-30492914f834.jpg)
Not working uninstall command

**Comment by shuence** [comment]
Try posting on Stalkoverflow 👀

**Comment by Gul733** [comment]
Try
pip install colorama
Then 
pip install pyngrok

Separately
Pip install -r requirement. Command doesn't work

**Comment by karma9874** [comment]
colorama is not required anymore in the latest androrat version
