### ISSUE TITLE
Regarding the signing error

### ISSUE THREAD

**Issue by vidhyasagar2410** [karma9874/AndroRAT#119]
![2022-01-30_16-27-31-c95eea7a04007cf8fbc329b48d6217d0](https://user-images.githubusercontent.com/71606336/151925392-529592bd-edbc-498d-b9b1-919ee24054d6.png)
Please help me out of this error

**Comment by lazengann86** [comment]
Needs Java 8

**Comment by vidhyasagar2410** [comment]
can u help to install java 8

**Comment by vidhyasagar2410** [comment]
and run the program in java 8

**Comment by lazengann86** [comment]
No like, Java 8 is a pre-req. I'm also stuck on the Java 8 installation

**Comment by vidhyasagar2410** [comment]
did this works to you

**Comment by lazengann86** [comment]
I have not been able to install Java 8

**Comment by aqibpk** [comment]
install java 8 by following command
sudo apt install openjdk-8-jdk

**Comment by jackjackraka** [comment]
when i installing java 8
here the errror

                                                                               
┌──(root💀raka)-[/home/rgc/Desktop/AndroRAT]
└─# sudo apt install openjdk-8-jdk                                        100 ⨯
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package openjdk-8-jdk
      


what i do pls help

**Comment by jackjackraka** [comment]
how can i contact you insta id h aapka pls help me

**Comment by jackjackraka** [comment]
> > > > when i installing java 8 here the errror
> > > > ┌──(root💀raka)-[/home/rgc/Desktop/AndroRAT] └─# sudo apt install openjdk-8-jdk 100 ⨯ Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package openjdk-8-jdk
> > > > what i do pls help
> > > 
> > > 
> > > What OS are you using?
> > > X86 KALI Debian 2021
> > > java ka version openjdk-jre 11
> > 
> > 
> > hiw can i contact you any Instagram id bro pls help me
> 
> I made an Ubuntu VM just for this tool and it worked perfectly fine the first time. Try with Ubuntu 20.04.3 LTS
> 
> https://ubuntu.com/download/desktop

ok
but how can u contact you again pls
give any contact info pls

**Comment by lazengann86** [comment]
> > > > > when i installing java 8 here the errror
> > > > > ┌──(root💀raka)-[/home/rgc/Desktop/AndroRAT] └─# sudo apt install openjdk-8-jdk 100 ⨯ Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package openjdk-8-jdk
> > > > > what i do pls help
> > > > 
> > > > 
> > > > What OS are you using?
> > > > X86 KALI Debian 2021
> > > > java ka version openjdk-jre 11
> > > 
> > > 
> > > hiw can i contact you any Instagram id bro pls help me
> > 
> > 
> > I made an Ubuntu VM just for this tool and it worked perfectly fine the first time. Try with Ubuntu 20.04.3 LTS
> > https://ubuntu.com/download/desktop
> 
> ok but how can u contact you again pls give any contact info pls

Through here my man

**Comment by VigneshSahoo** [comment]
> > > when i installing java 8 here the errror
> > > ┌──(root💀raka)-[/home/rgc/Desktop/AndroRAT] └─# sudo apt install openjdk-8-jdk 100 ⨯ Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package openjdk-8-jdk
> > > what i do pls help
> > 
> > 
> > What OS are you using?
> > X86 KALI Debian 2021
> > kali GNU/LINUX Rolling
> > java ka version openjdk-jre 11
> 
> hiw can i contact you any Instagram id bro pls help me

I am having the same issue. I am using Parrot OS
Linux parrot 5.14.0-9parrot1-amd64 #1 SMP Debian 5.14.9-9parrot1 (2021-10-26) x86_64 GNU/Linux

You can reach me in my Discord: VickyGod#7892

**Comment by SwitchAlpha** [comment]
01) Download Orale JDK 8
  //Link
https://www.oracle.com/en/java/technologies/javase/javase8-archive-downloads.html

02) Open Your Terminal(Ctrl + alt + T)

03) cd Downloads

04) sudo mkdir /usr/lib/jvm

05) cd /usr/lib/jvm

06) sudo tar -xvzf ~/Downloads/jdk-8u271-linux-x64.tar.gz

07) sudo gedit /etc/environment
(if your computer haven't gedit.. install using this command (sudo apt-get install gedit) )

08) After opened file,add followings command in your variable file

/usr/lib/jvm/jdk1.8.0_202/bin
/usr/lib/jvm/jdk1.8.0_202/db/bin
/usr/lib/jvm/jdk1.8.0_202/jre/bin

J2SDKDIR="/usr/lib/jvm/jdk1.8.0_202"
J2REDIR="/usr/lib/jvm/jdk1.8.0_202/jre"
JAVA_HOME="/usr/lib/jvm/jdk1.8.0_202"
DERBY_HOME="/usr/lib/jvm/jdk1.8.0_202/db"

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.8.0_202/bin:/usr/lib/jvm/jdk1.8.0_202/db/bin:/usr/lib/jvm/jdk1.8.0_202/jre/bin"
J2SDKDIR="/usr/lib/jvm/jdk1.8.0_202"
J2REDIR="/usr/lib/jvm/jdk1.8.0_202/jre"
JAVA_HOME="/usr/lib/jvm/jdk1.8.0_202"
DERBY_HOME="/usr/lib/jvm/jdk1.8.0_202/db"  

09) Save and close the file.

09) Enter the Following commands in your Terminal

sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0_202/bin/java" 0

sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.8.0_202/bin/javac" 0

sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0_202/bin/java

sudo update-alternatives --set javac /usr/lib/jvm/jdk1.8.0_202/bin/javac

10) Verify the setup

update-alternatives --list java

update-alternatives --list javac

11)Check the Java Version

java -version

**Comment by VigneshSahoo** [comment]
> Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.

![image](https://user-images.githubusercontent.com/54697837/153766068-fe54af75-87b4-413e-a1f9-501e6e3559eb.png)

Works perfectly now! Thanks for the quick fix.

**Comment by lazengann86** [comment]
> Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.

Works now!
Thanks!

**Comment by Gul733** [comment]
> Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.

Plz help 
Could not execute zipalign
![Screenshot_20220215-112936.png](https://user-images.githubusercontent.com/98087836/154006436-a68fb482-0dd6-4cec-b8c1-5db2df6c82bd.png)

**Comment by VigneshSahoo** [comment]
> > Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.
> 
> Plz help Could not execute zipalign ![Screenshot_20220215-112936.png](https://user-images.githubusercontent.com/98087836/154006436-a68fb482-0dd6-4cec-b8c1-5db2df6c82bd.png)

Presuming that you are using Parrot(the green colored lines 🍡 ), You probably don't have zipalign. It doesn't come pre-installed in Parrot. Check if it is installed or install it using sudo apt install zipalign. If it is installed, try running with the --debug option to get more logs.

**Comment by Gul733** [comment]
> > > Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.
> > 
> > Plz help Could not execute zipalign ![Screenshot_20220215-112936.png](https://user-images.githubusercontent.com/98087836/154006436-a68fb482-0dd6-4cec-b8c1-5db2df6c82bd.png)
> 
> Presuming that you are using Parrot(the green colored lines 🍡 ), You probably don't have zipalign. It doesn't come pre-installed in Parrot. Check if it is installed or install it using sudo apt install zipalign. If it is installed, try running with the --debug option to get more logs. 

I am using Termux

**Comment by Gul733** [comment]
> > > Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.
> > 
> > Plz help Could not execute zipalign ![Screenshot_20220215-112936.png](https://user-images.githubusercontent.com/98087836/154006436-a68fb482-0dd6-4cec-b8c1-5db2df6c82bd.png)
> 
> Presuming that you are using Parrot(the green colored lines 🍡 ), You probably don't have zipalign. It doesn't come pre-installed in Parrot. Check if it is installed or install it using sudo apt install zipalign. If it is installed, try running with the --debug option to get more logs. 

Problem solved
T
In Termux
Use pkg install aapt
To Install zipalign
I did this and
Apk signed successfully

**Comment by asimyahia10** [comment]
> > Added fix for this, now the signing should work with any java version, can anyone please verify the fix?.
> 
> Plz help Could not execute zipalign ![Screenshot_20220215-112936.png](https://user-images.githubusercontent.com/98087836/154006436-a68fb482-0dd6-4cec-b8c1-5db2df6c82bd.png) Termux

**Comment by mpb00** [comment]
> 

THANKS VRO IT WORKED
