### ISSUE TITLE
I am getting this error when building the apk

### ISSUE THREAD

**Issue by JustinT1188** [karma9874/AndroRAT#122]
Traceback (most recent call last):
  File "/home/justin/AndroRAT/androRAT.py", line 52, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/home/justin/AndroRAT/utils.py", line 370, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by abekuchbhi** [comment]
Am getting the same issue bro

**Comment by JustinT1188** [comment]
Install Java 8, it is the solution.

**Comment by abekuchbhi** [comment]
> 

How u installed it pls give me the command
