### ISSUE TITLE
interpreter commands not working

### ISSUE THREAD

**Issue by BaigHack3rss** [karma9874/AndroRAT#125]
I installed androRAT and got a connection but i can't execute commands.

![image](https://user-images.githubusercontent.com/77700401/153759927-51563962-0892-4123-9c3f-c22e001c8956.png)

**Comment by astridlol** [comment]
I'm also getting this same issue, I think it might be something to do with running Android v10+?

**Comment by JamiroFerrara** [comment]
Same. Tested on Android 9. Interpreter shell has no I/O. Connection works with both Ngrok and with self hosted server. 

Any advice would be appreciated!

**Comment by GhostAssassin10** [comment]
same problem I waited like 30mins and it's still not working

**Comment by coco4ttv** [comment]
Same problem
