### ISSUE TITLE
AndroRAT

### ISSUE THREAD

**Issue by mutungwa** [karma9874/AndroRAT#126]
Help with this problem
python3 androRAT.py --build -i 192.168.1.10 -p 4444 -o security.apk
Traceback (most recent call last):
File "androRAT.py", line 1, in
from utils import *
File "/home/kali/Downloads/AndroRAT/utils.py", line 12, in
from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by binary905** [comment]
try `pip3 install pyngrok`

**Comment by Gul733** [comment]
Install colorama and pyngrok separately by pip ie
pip install colorama
Then
pip install pyngrok
In AndroRat folder
Then 
Try

**Comment by Gul733** [comment]
Have you given permission
Like
 chmod +x * 

   in AndroRat

**Comment by Pradeepshah243** [comment]
python3 androRAT.py --build -i 127.0.2.15 -p 8000 -o unknown.apk
Traceback (most recent call last):
  File "androRAT.py", line 4, in <module>
    from utils import *
  File "/home/uknownan/AndroRAT/utils.py", line 61, in <module>
    os.makedirs("Dumps")
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'Dumps'

solution for this

**Comment by Ragnarloathbroak** [comment]
#python3 androRAT.py --build --ngrok -o evil.apk connection refused please help me with this
