### ISSUE TITLE
Trace back : (most recent calls) conf.get_default().monitor_thread = False

### ISSUE THREAD

**Issue by sai2730** [karma9874/AndroRAT#129]
python3 androRAT.py --build --ngrok -o evil.apk
Traceback (most recent call last):
  File "/root/Desktop/AndroRAT/androRAT.py", line 46, in <module>
    conf.get_default().monitor_thread = False
NameError: name 'conf' is not defined

**Comment by hack5711** [comment]
python3 androRAT.py --build --ngrok -o evil.apk
Traceback (most recent call last):
File "/root/Desktop/AndroRAT/androRAT.py", line 46, in
conf.get_default().monitor_thread = False
NameError: name 'conf' is not defined

**Comment by alaminrohman987** [comment]
Hre tyu meo jone riten place 😅

**Comment by wlvr44** [comment]
Hope this works
