### ISSUE TITLE
Error with this.

### ISSUE THREAD

**Issue by 123ysys** [karma9874/AndroRAT#132]
Hi
I got an error tip like this when I run python3 androRAT.py --build :
[1m[[31m[0m[1m[31mERROR[0m[1m][0m [1mpyngrok not found
[1m[[33m[0m[1m[33mINFO[0m[1m] [1mRun pip3 install -r requirements.txt
How to fix it? Thanks

**Comment by karma9874** [comment]
As its saying run  `pip3 install -r requirements.txt`

**Comment by 123ysys** [comment]
For backdoor(android side), should I build one for it? Or can I just download and install app-release.apk from Android_Code/app)/release ? Thank you.

**Comment by 123ysys** [comment]
> As its saying run `pip3 install -r requirements.txt`

And also I get these tips show 
```Requirement already satisfied: pyngrok in c:\users\administrator\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: PyYAML in c:\users\administrator\appdata\roaming\python\python310\site-packages (from pyngrok->-r requirements.txt (line 1)) (6.0)
```
 
after I ran the 
```pip3 install -r requirements.txt```
command, which seems that I have pre-installed before.
