### ISSUE TITLE
Android 11 Question

### ISSUE THREAD

**Issue by gieuci0x** [karma9874/AndroRAT#133]
Do you have in plan to update AndroRAT so it will work on android 11 version? Would be fantastic.

**Comment by karma9874** [comment]
Yes I do have a plan to update but not getting enough time to do so, maybe in future will update but yeah can't say for sure😅

**Comment by gieuci0x** [comment]
Great my friend we wait for your update. What exactly you need to do to get it work on android version 11? I just ask because I am curious :-)

**Comment by karma9874** [comment]
@gieuci0x  maybe find a someway to bypass this https://developer.android.com/about/versions/11/privacy/foreground-services
i guess
