### ISSUE TITLE
When am run it on termux it say Signing Failed

### ISSUE THREAD

**Issue by Mdsarowarhossain** [karma9874/AndroRAT#137]
Please help me . When am run it on termux it say Signing Failed
![Screenshot_20220226-020131](https://user-images.githubusercontent.com/98280301/155792105-6740a345-df45-4262-b087-92fef8d8af1a.png)

**Comment by karma9874** [comment]
#186

**Comment by Aaaaaqe** [comment]
karma9874 @karma9874 its doesnt work sstill please help

**Comment by Whitepanth** [comment]
I have also same problem please solve it
