### ISSUE TITLE
Shell BrokenPipeError

### ISSUE THREAD

**Issue by ladysans** [karma9874/AndroRAT#14]
Hi, I'm running AndroRAT on a Raspberry Pi 3B+. I built the APK using the Raspberry Pi's local IP and installed it on a Samsung Galaxy J3. 
When I start the shell, it says "Waiting for connections" for several minutes until it finds the phone and the interpreter is started. 
When I type in a command like deviceInfo (but any command really), it doesn't return anything. Then I type in a command for a second time and I get the following error:
Traceback (most recent call last):
 File "androRAT.py", line 90, in <module>
  conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe

Not sure how to fix it, can you help?

Cheers

**Comment by karma9874** [comment]
The issue seems to be with connection, I think the connection between the device and shell is not set properly
