### ISSUE TITLE
seems like the interpreter is not working but not sure why

### ISSUE THREAD

**Issue by stoneMajor64** [karma9874/AndroRAT#146]
![20220319_122124](https://user-images.githubusercontent.com/101314802/159108317-e4f127eb-727b-4311-8027-7fb4e02f3aee.jpg)

**Comment by mino2345** [comment]
Did you find a solution to this problem because I also suffer from it

**Comment by karma9874** [comment]
ConnectionResetError usually means that device is not able to connect to the client, maybe check if the internet is working or not.
