### ISSUE TITLE
Python was not found; 

### ISSUE THREAD

**Issue by echosvile** [karma9874/AndroRAT#147]
`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`

This still shows even after:
Adding to path
Disabling the shortcut from settings (Manage App Execution Aliases)
Uninstalling and and activate the add to path before installing
restarted the system
![androrat issue git](https://user-images.githubusercontent.com/71806009/159115337-3e474507-f9b5-42d7-8f6b-d96d51265831.png)

**Comment by karma9874** [comment]
Instead of python3 just try python androRAT.py and so on.

**Comment by echosvile** [comment]
i worked ahhhhhhhhh pants off bro... thank you so much


> Instead of python3 just try python androRAT.py and so on.
