### ISSUE TITLE
apk signing failed

### ISSUE THREAD

**Issue by asimyahia10** [karma9874/AndroRAT#149]
![Screenshot 2022-03-20 150910](https://user-images.githubusercontent.com/95473346/159163876-6b281b64-6adc-4d08-aa17-55dfce1c7820.png)

**Comment by asimyahia10** [comment]
How can i fix it??

**Comment by Sumankavya** [comment]
same problem

**Comment by CherylJacob** [comment]
Does anyone have an update on this? Same problem

**Comment by karma9874** [comment]
possible fix in #186

**Comment by bhushan93official** [comment]
![Screenshot_2022-10-09-18-16-24-659_com.termux.jpg](https://user-images.githubusercontent.com/87218745/194762761-fbab7dc2-2946-490a-8a50-eab5be3641ed.jpg)


How to fix it ?
