### ISSUE TITLE
Is it possible to make it fully compatible with android 10?

### ISSUE THREAD

**Issue by uGiFarukh** [karma9874/AndroRAT#15]
Hello,

Is it possible to make this project fully compatible with the latest Android 10 releases? That would help a lot. Please let me know if this project can be build for android 10 and can work inside android 10 without any problem. Thank You.

**Comment by karma9874** [comment]
Yup this project can be fully compatible with android 10 , just need to do some changes so that it can behave properly on 10

**Comment by uGiFarukh** [comment]
Hey @karma9874 is it possible for you to let me know what kind of changes? I am a coder myself but newbie to android. So I might be able to build the project under latest SDK and do necessary changes following android 10 documentations. Please let me know if I can help in any way. I also need this project fully compatible with Android 10 for one of my task.

**Comment by karma9874** [comment]
Actually even I dont know about where to change because i will be just doing error and try method 😅 on android 10 with all the features and fixing the issue where things don't works.
