### ISSUE TITLE
Need to update the version

### ISSUE THREAD

**Issue by 123ysys** [karma9874/AndroRAT#150]
Hi. I got a tip that shows "this app is built for an older version of Android, please contact the developer to update."

**Comment by biubiu0091** [comment]
@123ysys  i got the same problem.  really wonderring how to revise the Androrat codes to make it work on Android 12 ?

**Comment by 123ysys** [comment]
> @123ysys  i got the same problem.  really wonderring how to revise the Androrat codes to make it work on Android 12 ? 

I think it is because the targetSdk and minSdk are too low, in Android 10 they should>=23. I don't know what number is required on the Android 12.
