### ISSUE TITLE
Not able to download apk

### ISSUE THREAD

**Issue by SukhdevThukral** [karma9874/AndroRAT#152]
Tried downloading apk from the desired ip with port 4444 but the browser is saying refused to connect and I am using Apache 2 service for the server

**Comment by ImRkofficial** [comment]
Yes I have face this issue

**Comment by Midget-Man** [comment]
if your using apache2 you shouldnt have to display the port, when you go onto your phone go to the URL and simply type
"{IP ADDRESS}"/"Name of your apk file.apk" as long as you forwarded the apk file to /var/www/html/
So for example mine is             127.0.0.1/Alpha.apk and it should download easily as long as you have the antivirus offline
