### ISSUE TITLE
can.t connect ip address

### ISSUE THREAD

**Issue by ahmedsalehk** [karma9874/AndroRAT#154]
python3 androRAT.py --shell -i 192.168.1x.xx -p 8880
[ERROR]  [Errno 99] Cannot assign requested address

only work in 0.0.0.0 .... why ?

**Comment by karma9874** [comment]
When you bind localhost or 0.0.0.0, it means you can only connect to your service from local networks.
You cannot bind 192.168 because it does not belong to you, you can only bind IP owned by your computer
