### ISSUE TITLE
IT SAY PYNGROK NOT FOUND

### ISSUE THREAD

**Issue by Vinayak1939x** [karma9874/AndroRAT#155]
I AM USING SUDO BEFORE PYTHO3 AND EVRY OTHER COMMAND ARE SAME AND I TRIED EVERY THING PLS HELPPP!!!!!!!

**Comment by CherylJacob** [comment]
Do not use sudo before python3. I had the same issue, it works without

**Comment by Boss078** [comment]
Help me 
![IMG_20220523_111209](https://user-images.githubusercontent.com/106023065/169751148-082560ba-6f3f-4b8d-8fb2-618da4fb27c0.jpg)

**Comment by ravisinghtech2021** [comment]
[ERROR] pyngrok not found
error. plz help
