### ISSUE TITLE
how to inject AndroRAT backdoor into any normal apk & receive requests from multiple clients in shell mode & keep persistent session in android 10

### ISSUE THREAD

**Issue by czg6666666** [karma9874/AndroRAT#156]
Hello bro, Excuse me, how to inject AndroRAT backdoor into any normal apk & how to receive requests from multiple clients in shell mode & how to keep persistent session in android 10？

**Comment by mrtechie** [comment]
I am also unable to install the final apk on a Xioami Phone with Android 10 :(

**Comment by mrtechie** [comment]
it detects as a torjan virus
