### ISSUE TITLE
ihave error104 Traceback (most recent call last)

### ISSUE THREAD

**Issue by medyesbh** [karma9874/AndroRAT#165]
Traceback (most recent call last):
  File "/root/AndroRAT/androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
  File "/root/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by aranwa3** [comment]
> Traceback (most recent call last):
> 
>   File "/root/AndroRAT/androRAT.py", line 62, in <module>
> 
>     get_shell(args.ip,args.port) 
> 
>   File "/root/AndroRAT/utils.py", line 342, in get_shell
> 
>     conn.send(message_to_send.encode("UTF-8"))
> 
> ConnectionResetError: [Errno 104] Connection reset by peer

this happens when we exit the interpreter using ctrl+c. or your internet connection is not stable.
