### ISSUE TITLE
having issues while creating apk and apk is not downloading and showing this (could not execute zipalign Run with '--debug' parameter to get additional information.)

### ISSUE THREAD

**Issue by parthyadav51** [karma9874/AndroRAT#166]

**Comment by Louioui** [comment]
<img width="1618" alt="Screen Shot 2022-05-28 at 12 15 44 AM" src="https://user-images.githubusercontent.com/96560001/170834896-a75fab5d-c993-4a46-9ce0-3f95fe11147e.png">

**Comment by parthyadav51** [comment]
Yes I found it and I’m also not able to use l3mon can you help me with it?

**Comment by karma9874** [comment]
Possible fix in #186

**Comment by karma9874** [comment]
Possible fix in #186

**Comment by karma9874** [comment]
Possible fix in #186
