### ISSUE TITLE
App crashes on exit and shows white screen in victims phone

### ISSUE THREAD

**Issue by aranwa3** [karma9874/AndroRAT#167]
Hey karma I created payload using androrat and got a connection. It was not persistent and also the phone screen started flashing after I exit the interpreter. I used it on kali pi. also I think it has something to do with the java 8 builds. Please help

**Comment by karma9874** [comment]
Android Version?

**Comment by aranwa3** [comment]
android 11 nokia 3.4

**Comment by aranwa3** [comment]
thanks for replying
