### ISSUE TITLE
Trouble apk

### ISSUE THREAD

**Issue by jirokul** [karma9874/AndroRAT#170]
I'm using termux on android 11. apk build is successful, but apk file doesn't exist. Please help.
![androrat](https://user-images.githubusercontent.com/6198692/167277968-f740a1e6-f20e-41ad-bb2b-08f9dba1f531.png)

**Comment by rzgarespo** [comment]
change python3 to python

**Comment by GitStoopID** [comment]
Man I'm having the exact same issue and I get a zsh reply saying no such file exists!!!! WTH?! Did you ever figure this out?!

**Comment by GitStoopID** [comment]
Here is what I get ....
![IMG_20220612_233331](https://user-images.githubusercontent.com/107094051/173280308-f454d004-7eb2-45e0-81e6-9744b5b2fb36.jpg)

**Comment by mujahidshahani** [comment]
> change python3 to python

![Screenshot_2022-08-08-18-41-05-003_com termux](https://user-images.githubusercontent.com/108939978/183432099-f94296a2-1df8-4df1-8b66-adfec2eb268e.jpg)
Tried, but still not showing apk file.

**Comment by er-arunyadav** [comment]
I am also facing same issue..any one have solution for this?

**Comment by er-arunyadav** [comment]
I am also facing the same issue..any one have a solution for this?
