### ISSUE TITLE
Don't know what is wrong

### ISSUE THREAD

**Issue by addu2146** [karma9874/AndroRAT#176]
/AndroRAT$ python androRAT.py -h
Traceback (most recent call last):
  File "androRAT.py", line 4, in <module>
    from utils import *
  File "/home/a2146/AndroRAT/utils.py", line 186
    print(stdOutput("success")+f"Succesfully Uploaded the file \033[32m{filedata[0]+'.'+filedata[1]} in /sdcard/temp/")
                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by karma9874** [comment]
Use python3
