### ISSUE TITLE
unable to  connect to camera

### ISSUE THREAD

**Issue by schieferzahn** [karma9874/AndroRAT#177]
All works fine for me until i first get into the interpreter and type: CamList then: takepic 1 and when i do that i get the error: unable to connect to the camera.
After 3min in the interpreter it gives me this error after i type any command:
Traceback (most recent call last):
  File "/home/schiefer_zahn/AndroRAT/androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
  File "/home/schiefer_zahn/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe
i use wsl2 and portforwarding over ngrok 
pls help

**Comment by riska8899** [comment]
> All works fine for me until i first get into the interpreter and type: CamList then: takepic 1 and when i do that i get the error: unable to connect to the camera.
> After 3min in the interpreter it gives me this error after i type any command:
> Traceback (most recent call last):
>   File "/home/schiefer_zahn/AndroRAT/androRAT.py", line 62, in <module>
>     get_shell(args.ip,args.port) 
>   File "/home/schiefer_zahn/AndroRAT/utils.py", line 342, in get_shell
>     conn.send(message_to_send.encode("UTF-8"))
> BrokenPipeError: [Errno 32] Broken pipe
> i use wsl2 and portforwarding over ngrok 
> pls help

**Comment by gonzxph** [comment]
Same issue on me, any solution about this?

**Comment by Anton19881** [comment]
Did someone find the solution?

**Comment by HarshKumarweb** [comment]
same problem!!!!!!
