### ISSUE TITLE
> All works fine for me until i first get into the interpreter and type: CamList then: takepic 1 and when i do that i get the error: unable to connect to the camera.

### ISSUE THREAD

**Issue by riska8899** [karma9874/AndroRAT#181]
> All works fine for me until i first get into the interpreter and type: CamList then: takepic 1 and when i do that i get the error: unable to connect to the camera.
> After 3min in the interpreter it gives me this error after i type any command:
> Traceback (most recent call last):
>   File "/home/schiefer_zahn/AndroRAT/androRAT.py", line 62, in <module>
>     get_shell(args.ip,args.port) 
>   File "/home/schiefer_zahn/AndroRAT/utils.py", line 342, in get_shell
>     conn.send(message_to_send.encode("UTF-8"))
> BrokenPipeError: [Errno 32] Broken pipe
> i use wsl2 and portforwarding over ngrok 
> pls help

_Originally posted by @riska8899 in https://github.com/karma9874/AndroRAT/issues/177#issuecomment-1133781591_

**Comment by schieferzahn** [comment]
first you stole this comment from me and 2nd i have still this problem

**Comment by AnOnimus357** [comment]
> after installing the apk to phone, be sure you have allowed access to the camera of the phone. or find the app on the list of apps then allow everything that it requires.

I did all that but it still doesn't work, is there maybe another solution?

**Comment by Anton19881** [comment]
Did someone find the solution? @riska8899 @AnOnimus357 @schieferzahn

**Comment by AnOnimus357** [comment]
> Did someone find the solution? @riska8899 @AnOnimus357 @schieferzahn 

Nope ahahhahahahahha

**Comment by Anton19881** [comment]
> > Did someone find the solution? @riska8899 @AnOnimus357 @schieferzahn
> 
> Nope ahahhahahahahha

And do you know any alternative to AndroROT? I really need this :(

**Comment by AnOnimus357** [comment]
> > > Did someone find the solution? @riska8899 @AnOnimus357 @schieferzahn
> > 
> > Nope ahahhahahahahha
> 
> And do you know any alternative to AndroROT? I really need this :(

I really didn't.  I tried to find it everywhere but unfortunately I couldn't find it anywhere

**Comment by Anton19881** [comment]
> > > > Did someone find the solution? @riska8899 @AnOnimus357 @schieferzahn
> > > 
> > > 
> > > Nope ahahhahahahahha
> > 
> > 
> > And do you know any alternative to AndroROT? I really need this :(
> 
> I really didn't. I tried to find it everywhere but unfortunately I couldn't find it anywhere

It seems to work only with older android devices.

**Comment by Anton19881** [comment]
Hey @AnOnimus357 are you still interested in using this type of program? I found a much better and easier one.

**Comment by AnOnimus357** [comment]
> Hey @AnOnimus357 are you still interested in using this type of program? I found a much better and easier one. 

Really? Yes broo, who is it

**Comment by Anton19881** [comment]
> > Hey @AnOnimus357 are you still interested in using this type of program? I found a much better and easier one.
> 
> Really? Yes broo, who is it

Follow the instructions in the video (you can understand even if you don't speak Russian). It worked perfect for me. https://www.youtube.com/watch?v=NWoQaU0mya0 .Bro help bro 🤝

**Comment by AnOnimus357** [comment]
> > > Hey @AnOnimus357 are you still interested in using this type of program? I found a much better and easier one.
> > 
> > Really? Yes broo, who is it
> 
> Follow the instructions in the video (you can understand even if you don't speak Russian). It worked perfect for me. https://www.youtube.com/watch?v=NWoQaU0mya0 .Bro help bro 🤝

Thank you so much bro.God bles you

**Comment by SageTTs** [comment]
> > Hey @AnOnimus357 are you still interested in using this type of program? I found a much better and easier one. 
> 
> Really? Yes broo, who is it

I'm new to all this but I heard msfvenom works as well if you need help understanding you can watch loi liang yang or hacker loi on Youtube

**Comment by abdullahferozonline** [comment]
bro how to get connect again ? by typing commands.
