### ISSUE TITLE
Frequently gives error code BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by iqlessmemes** [karma9874/AndroRAT#182]
Usually when I am using this, I put in a command and it does nothing, then the next command I do, the thing breaks down and tells me: Traceback (most recent call last):
  File "androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
  File "/home/mileswhite/Desktop/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by schieferzahn** [comment]
exact same problem....

**Comment by 2973918177** [comment]
we have same question

**Comment by 2973918177** [comment]
so how to solve it ?

**Comment by Anton19881** [comment]
Did someone find the solution? @iqlessmemes @schieferzahn @2973918177

**Comment by iqlessmemes** [comment]
@Anton19881 no.
