### ISSUE TITLE
[ERROR] Signing Failed / could not execute zipalign - Run with '--debug' parameter

### ISSUE THREAD

**Issue by yayangkasepid** [karma9874/AndroRAT#186]
python3 androRAT.py --build -i 0.0.0.0 -p 8080 -o hehe.apk
[INFO] Generating APK
[INFO] Building APK |
[SUCCESS] Successfully apk built in /data/data/com.termux/files/home/AndroRAT/hehe.apk
[INFO] Signing the apk
[INFO] Signing Apk |
could not execute zipalign
Run with '--debug' parameter to get additional information.

[ERROR] Signing Failed

I used android 11

**Comment by Louioui** [comment]
I have the same issue !

**Comment by Louioui** [comment]
> python3 androRAT.py --build -i 0.0.0.0 -p 8080 -o hehe.apk [INFO] Generating APK [INFO] Building APK | [SUCCESS] Successfully apk built in /data/data/com.termux/files/home/AndroRAT/hehe.apk [INFO] Signing the apk [INFO] Signing Apk | could not execute zipalign Run with '--debug' parameter to get additional information.
> 
> [ERROR] Signing Failed
> 
> I used android 11
did you find any solution?

**Comment by daddydank99** [comment]
Exact problem here anyone figure it out?

**Comment by karma9874** [comment]
# Solution

**Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.

**Linux**: Just normal `apt-get install zipalign` should work.

**Termux**: Run `pkg install aapt`.

Hope this should help :)

**Comment by sainarravula575** [comment]
All good but I don't know how to download.The created application

**Comment by CayVb** [comment]
Tried all the fixes to zipalign but none work....can anyone create for me the app using this ip 192.168.0.103
caybenards@gmail.com (feedback)

**Comment by elizas6638** [comment]
> # Solution
> **Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.
> 
> **Linux**: Just normal `apt-get install zipalign` should work.
> 
> **Termux**: Run `pkg install aapt`.
> 
> Hope this should help :)

thanks, karma it's fixed...

**Comment by Hillellab** [comment]
> # Solution
> **Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.
> 
> **Linux**: Just normal `apt-get install zipalign` should work.
> 
> **Termux**: Run `pkg install aapt`.
> 
> Hope this should help :)

for kali linux, i tried apt-get as mentioned and it didnt work. try instead using `sudo apt install zipalign` and it should work just fine.

**Comment by AqidShah** [comment]
Zipalign is already installed
Have you found any solution to this error

**Comment by glare786** [comment]
> 

problem soll 🙏☺️Use apk Name is only evil.apk

**Comment by glare786** [comment]
> python3 androRAT.py --build -i 0.0.0.0 -p 8080 -o hehe.apk [INFO] જનરેટ કરી રહ્યું છે APK [INFO] બિલ્ડીંગ APK | [સફળતા] /data/data/com.termux/files/home/AndroRAT/hehe.apk માં apk સફળતાપૂર્વક બિલ્ટ [INFO] apk પર સહી કરવી [INFO] Apk પર સહી કરવી | વધારાની માહિતી મેળવવા માટે '--debug' પરિમાણ સાથે zipalign Run એક્ઝિક્યુટ કરી શક્યું નથી .
> 
> [ERROR] સહી કરવાનું નિષ્ફળ થયું
> 
> મેં એન્ડ્રોઇડ 11 નો ઉપયોગ કર્યો

Olny neme is  evil.apk  not adhar name use 🙏😊

**Comment by joepvd07** [comment]
I did the linux fix but it didn't work for me
sudo apt-get install zipalign
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libavfilter8 libavformat59 libplacebo208 libpostproc56 libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libspatialite7 libsuperlu5 libswscale6 libwebsockets17 python2-minimal python2.7-minimal python3-py
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  android-libbacktrace android-libbase android-libcutils android-liblog android-libutils android-libziparchive libzopfli1
The following NEW packages will be installed:
  android-libbacktrace android-libbase android-libcutils android-liblog android-libutils android-libziparchive libzopfli1 zipalign
0 upgraded, 8 newly installed, 0 to remove and 73 not upgraded.
Need to get 589 kB of archives.
After this operation, 2,046 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-liblog arm64 1:33.0.3-2 [36.5 kB]
Get:2 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-libbase arm64 1:33.0.3-2 [89.2 kB]
Get:3 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-libbacktrace arm64 1:33.0.3-2 [208 kB]
Get:4 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-libcutils arm64 1:33.0.3-2 [37.3 kB]
Get:5 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-libutils arm64 1:33.0.3-2 [53.7 kB]
Get:6 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 android-libziparchive arm64 1:33.0.3-2 [44.8 kB]
Get:7 http://ftp.belnet.be/pub/kali/kali kali-rolling/main arm64 libzopfli1 arm64 1.0.3-1 [91.2 kB]
Get:8 http://http.kali.org/kali kali-rolling/main arm64 zipalign arm64 1:10.0.0+r36-1 [27.9 kB]
Fetched 589 kB in 1s (466 kB/s)     
Selecting previously unselected package android-liblog:arm64.
(Reading database ... 459236 files and directories currently installed.)
Preparing to unpack .../0-android-liblog_1%3a33.0.3-2_arm64.deb ...
Unpacking android-liblog:arm64 (1:33.0.3-2) ...
Selecting previously unselected package android-libbase:arm64.
Preparing to unpack .../1-android-libbase_1%3a33.0.3-2_arm64.deb ...
Unpacking android-libbase:arm64 (1:33.0.3-2) ...
Selecting previously unselected package android-libbacktrace:arm64.
Preparing to unpack .../2-android-libbacktrace_1%3a33.0.3-2_arm64.deb ...
Unpacking android-libbacktrace:arm64 (1:33.0.3-2) ...
Selecting previously unselected package android-libcutils:arm64.
Preparing to unpack .../3-android-libcutils_1%3a33.0.3-2_arm64.deb ...
Unpacking android-libcutils:arm64 (1:33.0.3-2) ...
Selecting previously unselected package android-libutils:arm64.
Preparing to unpack .../4-android-libutils_1%3a33.0.3-2_arm64.deb ...
Unpacking android-libutils:arm64 (1:33.0.3-2) ...
Selecting previously unselected package android-libziparchive:arm64.
Preparing to unpack .../5-android-libziparchive_1%3a33.0.3-2_arm64.deb ...
Unpacking android-libziparchive:arm64 (1:33.0.3-2) ...
Selecting previously unselected package libzopfli1.
Preparing to unpack .../6-libzopfli1_1.0.3-1_arm64.deb ...
Unpacking libzopfli1 (1.0.3-1) ...
Selecting previously unselected package zipalign.
Preparing to unpack .../7-zipalign_1%3a10.0.0+r36-1_arm64.deb ...
Unpacking zipalign (1:10.0.0+r36-1) ...
Setting up android-liblog:arm64 (1:33.0.3-2) ...
Setting up libzopfli1 (1.0.3-1) ...
Setting up android-libbase:arm64 (1:33.0.3-2) ...
Setting up android-libziparchive:arm64 (1:33.0.3-2) ...
Setting up android-libcutils:arm64 (1:33.0.3-2) ...
Setting up android-libbacktrace:arm64 (1:33.0.3-2) ...
Setting up android-libutils:arm64 (1:33.0.3-2) ...
Setting up zipalign (1:10.0.0+r36-1) ...
Processing triggers for libc-bin (2.37-6) ...
Processing triggers for man-db (2.11.2-3) ...
Processing triggers for kali-menu (2023.4.2) ...
Scanning processes...                                                                                                                                                                                                             
Scanning linux images...                                                                                                                                                                                                          

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
                                                                                                                                                                                                                                  
┌──(joepvandessel㉿kali)-[~/AndroRAT]
└─$ python3 androRAT.py --build -i 192.168.64.4 -p 4444 -o joep.apk
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /home/joepvandessel/AndroRAT/joep.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
could not execute zipalign
Run with '--debug' parameter to get additional information.

[ERROR] Signing Failed

can anyone help me

**Comment by CODonnie** [comment]
how do you move the apk to local after it's been built

**Comment by Gourav8078** [comment]
Just install aapt

**Comment by Gourav8078** [comment]
> how do you move the apk to local after it's been built

Did you get that ?

**Comment by davidad81** [comment]
sudo apt remove zipalign

then try again it will works

**Comment by mohammadakram0705** [comment]
could not execute **zipalign**

 same problem i got  see the screenshot
  


**THE SOLUTION IS** 
 

YOU COULD REMOVE THE zipalign USING THE FOLLOWING CODE



IN KALI LUNIX :    



    sudo apt remove zipalign



AFTER I WILL PASTE THE CODE 
I GOT SUCESS SEE IN THE SCEENSHOT






 IF GOT THIS SAME ERROR YOU WILL CONTACT ME

**Comment by TimmieBimmie** [comment]
> how do you move the apk to local after it's been built
If you want to move the apk to an other place in your linux system, you can just type the following: "sudo mv /*mounting-point* /*where you want it to be*

**Comment by TimmieBimmie** [comment]
> how do you move the apk to local after it's been built

If you want to move the apk to an other place in your linux system, you can just type the following: "sudo mv /mounting-point /where you want it to be

**Comment by guyan11122222** [comment]
我的apk 签名成功了 但是在安卓上安装失败，不知道是为什么

**Comment by bayer7777** [comment]
I got same problem but none of the solutions above worked. It still says this. 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
could not execute zipalign
Run with '--debug' parameter to get additional information.

**Comment by jawadnaq** [comment]
did you get a solution? i have the same issue as you im on kali 


> I got same problem but none of the solutions above worked. It still says this. Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true could not execute zipalign Run with '--debug' parameter to get additional information.

**Comment by saalim24** [comment]
Launch another instance of terminal and use `sudo apt-get remove zipalign` then try again.
It worked for me.

**Comment by AvkaranGabbi** [comment]
still not solved anyone please help
already tried https://github.com/karma9874/AndroRAT/issues/186#issuecomment-1153133754

**Comment by L-lawliet76** [comment]
> could not execute **zipalign**
> 
> I GOT THE SAME PROBLEM
> 
> **THE SOLUTION IS**
> 
> YOU COULD REMOVE THE zipalign USING THE FOLLOWING CODE
> 
> IN KALI LUNIX :
> 
> ```
> sudo apt remove zipalign
> ```
> 
> AFTER I WILL PASTE THE CODE
> 
> I GOT SUCESS
> 
> IF ANYBODY GOT THIS SAME ERROR YOU WILL CONTACT ME

This solved the problem i was facing ,try this guys . it might work for you as well.

**Comment by AvkaranGabbi** [comment]
I have tried this, it doesn't work
It still shows:

Picked up _JAVA_OPTIONS: Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
could not execute zipalign
Run with '--debug' parameter to get additional information.

[ERROR] Signing Failed

**Comment by HipsterChipster** [comment]
I am using Kali on my Mac Book Pro and ran this and got the same error message that everyone else was getting and then I removed zipalign, reinstalled it, update -y'd that batch and rebooted and then it was fine. Signed success.![20240320_032128.jpg](https://github.com/karma9874/AndroRAT/assets/108474510/d941a80f-aaaf-49ee-9938-0f2474fc81f4)

**Comment by 15w34r0n3D4y** [comment]
Without errors works on Samsung A23 with Termux (from F-Droid) used aapt2 and sign.jar v1.3.0 with Java v17, but don't works on nethunter (kali) with zipalign because get error "could not execute zipalign".

AndroRAT create .apk file but zipalign maybe can't found it and that's why can't execute.

**Comment by Diloshan01** [comment]
> # Solution
> **Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.
> 
> **Linux**: Just normal `apt-get install zipalign` should work.
> 
> **Termux**: Run `pkg install aapt`.
> 
> Hope this should help :)

Thank You very much , It's Working

**Comment by Kevinsathvik182** [comment]
Still not working

**Comment by joelindra** [comment]
I got same error 

![image](https://github.com/user-attachments/assets/0d59eff3-80c6-45a5-8989-8b19d26b86ed)

How to solve ?
Try this!

`sudo apt remove zipalign`

![image](https://github.com/user-attachments/assets/0ac7071f-69c4-40f4-a47d-e63b6f18a3c5)

and try again, it will working good

![image](https://github.com/user-attachments/assets/b4174dcd-ea2c-4768-a498-aaf74d42b159)

**Comment by MikasaSickoMode** [comment]
> # Solution
> **Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.
> 
> **Linux**: Just normal `apt-get install zipalign` should work.
> 
> **Termux**: Run `pkg install aapt`.
> 
> Hope this should help :)

still doesnt work after unzipping the build tool version 30.0.0 and adding it to the environment path still shows that it cannot execute the zipalign

**Comment by werdexs** [comment]
**`If someone still gets this error 
on kali linux`**

1. Remove zipalign
```
sudo apt remove zipalign
```
2. Go to apt sources list
```
sudo nano /etc/apt/sources.list
```
3.Add Ubuntu package sources and comment kali sources

Add # to kali source

Scroll to end and add 
```
deb http://ftp.de.debian.org/debian buster main
```
4. Update
```
sudo apt update
```
5.Install it again
```
sudo apt install zipalign
```

6.Check if androrat started 
working

7.In the end delete Ubuntu sources  from /etc/apt/sources.list and uncomment kali source

```
sudo nano /etc/apt/sources.list
```

Remove the # from kali source and run update

I tried everything in comments, but it didn't helped me
It's because zipalign from kali sources is broken as I think

I hope this will help you

**Comment by sahil09a** [comment]
> # Solution
> **Windows**: [Download](https://androidsdkmanager.azurewebsites.net/Buildtools) build tools 30, unzip and add the directory to your environment path. Then run the AndroRAT.
> 
> **Linux**: Just normal `apt-get install zipalign` should work.
> 
> **Termux**: Run `pkg install aapt`.
> 
> Hope this should help :)

sir i have tried this in termux but it didn't work

**Comment by sahil09a** [comment]
~/Androrat $ python3 androRAT.py --build -i 192.168.29.63
-p 5555

[INFO] Generating APK

[INFO] Building APK

[SUCCESS] Successfully apk built in /data/data/com.termux/f

iles/home/Androrat/karma.apk

[INFO] Signing the apk

[INFO] Signing Apk

could not load embedded debug keystore: No such file or directory

Run with
'--debug' parameter to get additional information.

[ERROR] Signing Failed

please help me anyone i have installed aapt but i have not found any solution .

**Comment by nabilqw** [comment]
الحل 

> # حل
> **ويندوز** : [نزّل](https://androidsdkmanager.azurewebsites.net/Buildtools) أدوات البناء 30، وفكّ ضغط الملف، ثم أضفه إلى مسار بيئة التشغيل. ثم شغّل AndroRAT.
> 
> **Linux** : `apt-get install zipalign`يجب أن يعمل الوضع الطبيعي فقط.
> 
> **Termux** : تشغيل `pkg install aapt`.
> 
> آمل أن يساعد هذا :)

I actually succeeded after this

**Comment by enayetmolla845-dev** [comment]
Hi

**Comment by ghost** [comment]
Open the platform-tool folder in terminal and use there the uber-apk-signer-1.3.0.jar and its work
