### ISSUE TITLE
Live updating

### ISSUE THREAD

**Issue by chasefan3709** [karma9874/AndroRAT#188]
I use AndroRAT and it's up and running the only issue I have with it is that it only works when the phone is connected to my home Wi-Fi where the computer is hardwired if the phone is not connected to the Wi-Fi it doesn't work or won't connect how can I fix that

**Comment by Kali95739** [comment]
Learn about lan vs wan

**Comment by chasefan3709** [comment]
> Learn about lan vs wan

so after i build it i would --shell --ngrok?

**Comment by Kali95739** [comment]
Need to be on the correct interface to for your operating system my bad just saw message yea try ngrok long as not need to forward more then one port either by going to admin portal or contacting your wifi isp
