### ISSUE TITLE
Building Failed 

### ISSUE THREAD

**Issue by espanista** [karma9874/AndroRAT#19]
Bonjour,
J'utilise Nethunter on Termux , j'ai un problème pendant la génération du Apk.  Java 8 est installé.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_10460194248698115624.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL3232415382178560490.tmp, -e, /tmp/APKTOOL243148447067492218.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/AndroRAT/Compiled_apk_files/res, -M, /root/AndroRAT/Compiled_apk_files/AndroidManifest.xml]

**Comment by karma9874** [comment]
I m not sure about kali net hunter, I haven't tested on it 😅. Can you try it on any other platform (windows or Linux )

**Comment by lachin58** [comment]
![Uploading py.jpg…]()

**Comment by lachin58** [comment]
help me about this error
