### ISSUE TITLE
The Android 12 version has enabled location permissions, but getLocation cannot be used

### ISSUE THREAD

**Issue by yinglian-litao** [karma9874/AndroRAT#193]
The Android 12 version has enabled location permissions, but getLocation cannot be used

**Comment by mlemmlemquynh** [comment]
bruh are u did read the limited android can be get full access in this tool,in android 11 or 12 permission will limited

**Comment by yinglian-litao** [comment]
GPS Permission is enabled

**Comment by yinglian-litao** [comment]
> bruh are u did read the limited android can be get full access in this tool,in android 11 or 12 permission will limited

Permission is enabled

**Comment by Jam1e432** [comment]
Does it still work at somethings in android 12?
