### ISSUE TITLE
Waiting for connections is lasting 4ever

### ISSUE THREAD

**Issue by MULTI-GAMER-2** [karma9874/AndroRAT#199]
Hello Devs.
I was trying to use on my real phone this software but it just keep saying "Waiting for connections" and never load my phone as a connection (btw my pc os is windows). Idk what happened.
Thx

**Comment by haider890** [comment]
I also got the same problem

**Comment by haider890** [comment]
I also got the same problem

**Comment by haider890** [comment]
> Hello Devs. I was trying to use on my real phone this software but it just keep saying "Waiting for connections" and never load my phone as a connection (btw my pc os is windows). Idk what happened. Thx

Bruh did it started working for you and if it is tell me how you have started.

**Comment by haider890** [comment]
> > > Hello Devs. I was trying to use on my real phone this software but it just keep saying "Waiting for connections" and never load my phone as a connection (btw my pc os is windows). Idk what happened. Thx
> > 
> > 
> > Bruh did it started working for you and if it is tell me how you have started.
> 
> I have already fixed that error. It was just a mistake from my side. My ipconfig has changed bc of other router inside my house and I didn't knew (instead of, for example, this IP 192.168.0 I have written this one 192.0.168)!

Can you please help me with that?

**Comment by Faceinter** [comment]
Clonning it on my iphone is not working using ish software
