### ISSUE TITLE
Request Feature : PortForwarding

### ISSUE THREAD

**Issue by zulfi0** [karma9874/AndroRAT#20]
hello !

Can you please add a feature portforwarding between server and client ?? please let me know if you wish.

awsome project btw <3

**Comment by soyabkhanmalek** [comment]
For any RAT server running locally you have to set port forwarding manually. You can do it with portmap.io i tested this rat with it and it works perfectly.

**Comment by zulfi0** [comment]
i mean like portfwd in meterpreter, if portfwd like that ofc i know bruh..
and have you tried the rat in any different version android ? for me in android 9-10 the rat is running but it didn't give me any interpreter.

**Comment by karma9874** [comment]
Will try to include it in next version, thanks for suggestion :)

**Comment by karma9874** [comment]
MIUI force closes the app when it is running in the background for battery performance boost so you need to disable it 😅 for it to work

**Comment by gladiatori** [comment]
I tryed with portmap but doesn't work

**Comment by sahillimba** [comment]
> For any RAT server running locally you have to set port forwarding manually. You can do it with portmap.io i tested this rat with it and it works perfectly.

bhai portmap use kerke konsa ip or port use kerna hai

**Comment by Xerox563** [comment]
> For any RAT server running locally you have to set port forwarding manually. You can do it with portmap.io i tested this rat with it and it works perfectly.

can you help me how to do it
