### ISSUE TITLE
root access

### ISSUE THREAD

**Issue by MrRage18** [karma9874/AndroRAT#202]
I'm not sure if this is an issue. More of me not knowing most likely, but is there a way to access the root file system using the shell. I know how to access the cd /sdcard. I want to be able to install apk and other files as well as access the root. Maybe even root the android through the shell? If that is possible.

**Comment by krisdowis** [comment]
It is possible depending on the android version

**Comment by funnu0001** [comment]
hello coders please help me when my apk is buil in androrat successfully but its location is root/AndroRAT/evil.apk and when i open the root folder his does not open its saying it was denied. so what i m do please help me.................

**Comment by krisdowis** [comment]
sudo mv (apk location (new location)
