### ISSUE TITLE
give all permission still (waiting for connection) check pics

### ISSUE THREAD

**Issue by HammadRaja707** [karma9874/AndroRAT#209]
![WhatsApp Image 2022-08-07 at 4 11 41 AM](https://user-images.githubusercontent.com/105307476/183282329-fc84b7e2-de48-4c27-abf4-ce9f16c714dd.jpeg)
![WhatsApp Image 2022-08-07 at 4 11 30 AM](https://user-images.githubusercontent.com/105307476/183282331-24545699-b5dc-4f8f-8313-375177b0f068.jpeg)
Gi[](url)

**Comment by avirils** [comment]
Am having the same problem

**Comment by avirils** [comment]
Am having the same issue
