### ISSUE TITLE
RAT is running but doesn't give any interpreter mode

### ISSUE THREAD

**Issue by zulfi0** [karma9874/AndroRAT#21]
hi, i face a problem where the rat is running but it doesn't give me any interpreter mode. i have give access to ignore battery optimization and the icon, first time i install the rat the icon is dissapear but after a few hours the icon is appear.
i have check my ip and port  inside the rat, everything is right. 
is it bug or something ??

`device   : redmi 5 plus`
`android : 8.1`

i tried to another phone which has `android 5` and i got the same problem too

**Comment by karma9874** [comment]
I tested it on redmi 8.1 android and it worked fine for me, I guess there is an issue with you IP or port and the reappear of the icon after sometime is not possible coz. If there was some issue then the app should have been crashed not reappearance of the icon coz I never coded for reappearance of that icon

**Comment by zulfi0** [comment]
thank for your time sir..
this is the screenshot when the app is reappear 
![Cuplikan Layar_2020-08-31_20-49-55](https://user-images.githubusercontent.com/68773572/91721899-afdf0480-ebc3-11ea-932c-583a87f06d36.png)         ![Cuplikan Layar_2020-08-31_20-50-12](https://user-images.githubusercontent.com/68773572/91721925-bd948a00-ebc3-11ea-97dd-8f5ed31ef9fb.png)

![Cuplikan Layar_2020-08-31_20-50-26](https://user-images.githubusercontent.com/68773572/91722013-db61ef00-ebc3-11ea-8402-dd20683011cb.png)
even it doesn't need an hour to reappear

**Comment by zulfi0** [comment]
hey after a few tried it is working perfectly, the icon is not reappear again and i got interpreter mode when ever i open up my listener, the problem is on my phone. i don't know what happened to my phone but after reboot the app working perfect..
thank's for your time sir and i'm sorry if it bother you.
