### ISSUE TITLE
Connection Problem  for  AndroRAT 

### ISSUE THREAD

**Issue by follow-prince** [karma9874/AndroRAT#213]
****please support *******

1. ** error**                                                                                    

[INFO] Waiting for Connections  |                                                                                                      
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  —
[INFO] Waiting for Connections  |
[INFO] Waiting for Connections  —
[INFO] Waiting for Connections  |
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  —
[INFO] Waiting for Connections  /
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  —
[INFO] Waiting for Connections  |
[INFO] Waiting for Connections  \
[INFO] Waiting for Connections  —
[INFO] Waiting for Connections  \

![Screenshot_2022-08-16-23-26-05-636_com offsec nethunter kex](https://user-images.githubusercontent.com/105858216/184948782-3fd3e718-9a77-4426-8866-782757f74a03.jpg)

**Comment by Therealgubbi** [comment]
Because it not help and i Got hacked and restart my computer and the Mobile
on

tirsdag den 16. august 2022 skrev i-am-elango ***@***.***>:

**Comment by zusekid** [comment]
same issue
