### ISSUE TITLE
Connection Reset Error -104

### ISSUE THREAD

**Issue by psybervac** [karma9874/AndroRAT#214]
How to restart the connection. I had it to working for a while but after some time i lost the connection. How to remotely start the connection?

**Comment by Therealgubbi** [comment]
What u mean and ho are u?

tor. 18. aug. 2022 kl. 11.35 skrev psybervac ***@***.***>:

**Comment by Therealgubbi** [comment]
Iam hacked right now Can u see it

lørdag den 20. august 2022 skrev Tobias Haugaard ***@***.***>:

**Comment by Therealgubbi** [comment]
What is our Hole messengs? Iam sure i find something right before there was
not me

torsdag den 18. august 2022 skrev psybervac ***@***.***>:
