### ISSUE TITLE
New version of androRAT 

### ISSUE THREAD

**Issue by aleeessio** [karma9874/AndroRAT#215]
If you can it would be great to update the tool to support android 11 and 12 too. I've tested it on android 11 and options that worked were only deviceInfo, camList, getCallLogs, shell, and getSms. In addition the phone gives a message that says that the apk is made for a previous version of android. Thanks for reading my suggestion :)

**Comment by karma9874** [comment]
Really wanted to work on the upgrade, but yeah not getting enough time from the work life 😅.

**Comment by aleeessio** [comment]
> Really wanted to work on the upgrade, but yeah not getting enough time from the work life 😅.

Yeah don't worry, when your work life   will let you do it, you'll do it. However thanks for publishing this very useful script :)

**Comment by heymrlen** [comment]
Thank you for this wonderful creation 😊👏👏👏

**Comment by Jam1e432** [comment]
Hi mate the app looks amazing out of all the ones ive seen it looks the best/easiest to use id love to see this working on the lastest devices if you ever do get chance
