### ISSUE TITLE
AndroRAT apk can't get installed on the users phone 

### ISSUE THREAD

**Issue by AtillaDev** [karma9874/AndroRAT#216]
All the phones I tried to infect (with permission) also get this issue or a message that is recognized as a virus and cant get installed.

**Comment by Tx-800** [comment]
so androrat is useless now??

**Comment by AtillaDev** [comment]
Pretty much

**Comment by AtillaDev** [comment]
Pretty much

**Comment by Therealgubbi** [comment]
Is androrat complete installede whit the (codes) if i have the GitHub
desktop and the androrat in there?

søn. 4. sep. 2022 kl. 21.20 skrev Atila ***@***.***>:

**Comment by dodidahri** [comment]
same issue here i have sent it to my android through WhatsApp when i tried to open file Whatsapp showed an error that (you may not have a proper app to view this )
