### ISSUE TITLE
Error Pyngrok Not Found and it's installed

### ISSUE THREAD

**Issue by StormTheXef** [karma9874/AndroRAT#217]
![Screenshot_20220821-155219](https://user-images.githubusercontent.com/103287938/185794312-00d1cc7d-c1e0-4347-b640-8420b4a644b4.png)
How?

**Comment by aleeessio** [comment]
> ![Screenshot_20220821-155219](https://user-images.githubusercontent.com/103287938/185794312-00d1cc7d-c1e0-4347-b640-8420b4a644b4.png)
> How?

Try again
sudo pip3 install pyngrok

Check if the module has been installed in a oldest version of python, and maybe it's not installed in the current version

**Comment by StormTheXef** [comment]
Hello, i tryed it like 500 times and the same thing and i updated py to the latest version so what?
@aleeessio

**Comment by acecard0810** [comment]
Is there still no update on the issue? Cause i have been getting the same error. Is it because i'm using it on a virtual box?

**Comment by Shivonje** [comment]
> Is there still no update on the issue? Cause i have been getting the same error. Is it because i'm using it on a virtual box?

Having the exact same error here.
Did you resolve the issue?

**Comment by deloam** [comment]
[USANDO MAC] para resolver isso eu peguei a pasta que esta instalado o pyngrok e joguei na pasta onde está o androRAT, assim o androRAT.py conseguiu resolver essa dependencia sem precisar fazer mais nada.

`/opt/homebrew/lib/python3.11/site-packages/pyngrok
`
no meu caso fica nessa localização, dentro dele a uma outra pasta que fiz a mesma coisa, copiei os arquivos dela e coloquei na pasta correspondente dentro da pasta do androRAT, ou seja podemos fazer assim, já levar o pyngrok dentro do git

**Comment by Sudharshan0207** [comment]
![image](https://user-images.githubusercontent.com/101191173/235640861-65ad73e7-0ab4-467a-8773-87a0fd5429b8.jpg)
Still i am getting the same error please solve this and post the solution

**Comment by aleeessio** [comment]
> Hello, i tryed it like 500 times and the same thing and i updated py to the latest version so what?
> @aleeessio 

Maybe you've to add to path the folder of python packages

**Comment by Sabi0014** [comment]
![Screenshot 2024-12-03 163033](https://github.com/user-attachments/assets/2595c83a-5c85-469c-acd6-0bf5e789f842)
i have some problem can u plz tell somthing

**Comment by Sabi0014** [comment]
Having the exact same error here.
Did you resolve the issue

**Comment by electrontech1** [comment]
you actually need to install pyngrok directly to the AndroRAT dir by running "pip install -r requirements.txt --target=." this should fix the error
