### ISSUE TITLE
Getting a error "Signing failed" while signing the apk can you please help me out.!!??

### ISSUE THREAD

**Issue by pjpalaaash** [karma9874/AndroRAT#22]
While signing apk it is showing signing failed

**Comment by karma9874** [comment]
Any error?

**Comment by cymilad** [comment]
![Capture](https://user-images.githubusercontent.com/22496001/93018298-ed8c5600-f5e3-11ea-8140-9e943747cdbc.JPG)

**I have this problem too**

**Comment by karma9874** [comment]
You are using java 9, use java 8

**Comment by Crazyoh123** [comment]
But still showng same error can you able to help

**Comment by Crazyoh123** [comment]
![Screenshot at 2021-12-07 14-27-26](https://user-images.githubusercontent.com/90847001/145042294-e29e1a10-9f05-49bd-a705-6af627f5d295.png)

**Comment by Louioui** [comment]
> Can you show the full error?
<img width="1618" alt="Screen Shot 2022-05-28 at 12 15 44 AM" src="https://user-images.githubusercontent.com/96560001/170815026-588b3ac7-dd87-444c-a63a-3b8d08d0af9c.png">

-

**Comment by Louioui** [comment]
any hints you can give me to fix this ?

**Comment by daddydank99** [comment]
Getting exact same error
