### ISSUE TITLE
python3 androRAT.py --build --ngrok -p 8000 -0 unknown.apk usage: androRAT.py [--build] [--shell] [-i <IP> -p <PORT> -o <apk name>] androRAT.py: error: unrecognized arguments: -0 unknown.apk

### ISSUE THREAD

**Issue by Pradeepshah243** [karma9874/AndroRAT#230]
python3 androRAT.py --build --ngrok -p 8000 -0 unknown.apk
usage: androRAT.py [--build] [--shell] [-i <IP> -p <PORT> -o <apk name>]
androRAT.py: error: unrecognized arguments: -0 unknown.apk

solution for this plz

**Comment by nickfour** [comment]
-o ✓ not zero -0 **
