### ISSUE TITLE
update for android 12

### ISSUE THREAD

**Issue by Pradeepshah243** [karma9874/AndroRAT#231]
please update this for android 12 also

**Comment by Dewtah** [comment]
same :P

**Comment by karma9874** [comment]
same xD

**Comment by rohitrvayuz** [comment]
? @karma9874

**Comment by karma9874** [comment]
I don't currently have any specific plans for this, but I'm open to PR. Feel free to contribute!

**Comment by rohitrvayuz** [comment]
Glad to know it is still active.

Thanks.

Any references to read or learn to make it available for latest android

Regards,
Rohit Rajput
Project Lead - Mobile Technologies | VAYUZ Technologies
***@***.*** | Skype: business.vayuz

**Comment by karma9874** [comment]
I'm unsure about the Android API changes in the latest version. I'll consider reviewing the Android 12 SDK to identify any new updates and implement them in this code

**Comment by HyperNinjaProX** [comment]
why does it crash on andriod 11 when running some payloads through shell. After the service crashes i have to completely reinstall the apk by deleting it first. It wont boot up at start or after crash. Dose this have something to do with android version which android version dose this run smoothly on
