### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by Salidor** [karma9874/AndroRAT#24]
Hey, I just wanted to test it out. When I try to run the shell mode it just shows me "Waiting for Connections" and nothing happens.
I installed the created apk in my phone. Could you pls tell me what IP addresses I should put **To build the apk** and **To get the interpreter**? Many Thanks.

**Comment by karma9874** [comment]
To build the apk -> local machine IP with port forwarding
To get the interpreter -> 0.0.0.0

**Comment by Salidor** [comment]
Thank you for your quick reply @karma9874 . I did as you said it worked. I'm testing it in samsung galaxy A51 (Android 10). After apk installation it opens the interpreter. Checked some functions like call logs camList etc (worked fine) but getLocations didn't work. When I tried to run the interpreter for the second time it just stucks on "waiting for connections". Is it something you faced before or I'm doing something wrong? Thank you again.

**Comment by Salidor** [comment]
After some time it connects again but gives me error when i try any functions:
```
Interpreter:/> camList
Traceback (most recent call last):
  File "androRAT.py", line 89, in <module>
    conn.send(message_to_send.encode("UTF-8"))
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by karma9874** [comment]
getLocations on Android 10 is buggy 😅 . Sometimes it works and sometimes it not it also crashes the app I guess, so you will need to install the whole app again and then set the interpreter. I will try to fix this bug asap 😅

**Comment by Salidor** [comment]
Yes, you're perfectly right it is crashes soon after that :) Another issue needs to be taken into account is app is not being installed in some phones (tested on galaxy S7 and A 31) it just installing it all the time, but eventually it isn't. Any solutions for it? Thanks a lot,

**Comment by Ir786106** [comment]
**I created an APK file and started a Python HTTP server. The server is running, and I can access a test file from my phone using **http://192.x.x.x:8xxx/test.txt**. However, I cannot access or use the APK as expected from my phone. Both my Kali VM and my Android phone are connected to the same Wi-Fi network. Kali is running in VMware with Bridged networking. How can I troubleshoot this issue?**
