### ISSUE TITLE
ay dont skip

### ISSUE THREAD

**Issue by Adamladeb** [karma9874/AndroRAT#248]
Interpreter:/> camList
Traceback (most recent call last):
  File "C:\androRAT_RAT\androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\androRAT_RAT\utils.py", line 340, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by Adamladeb** [comment]
I trayed it on memu play

**Comment by gogo0418** [comment]
I'm having same problem.
