### ISSUE TITLE
Port forwarding 

### ISSUE THREAD

**Issue by claudiaDent** [karma9874/AndroRAT#25]
Is it possible to make a connection between router and mobile phone internet? I created port in my pc and interpreter works only when mobile phone connected to this wi-fi, where this port was created. When mob phone uses mobile internet, the interpreter isn’t working. Nice work but it needs to be improved😊

**Comment by zulfi0** [comment]
so u want to use it over wan right ?? if so u can use portmap

**Comment by karma9874** [comment]
Port forwarding can be done from your ISP only or you can ngrok
