### ISSUE TITLE
How to bind it with another apk

### ISSUE THREAD

**Issue by AndroRat999877** [karma9874/AndroRAT#251]
HOW to bind AndroRat with another APK ? Can someone help me please..

**Comment by AndroRat999877** [comment]
Same

**Comment by iamvikashh** [comment]
For that, you need to decompile the other apk( using apktool) and edit its smalli code in order to trigger the AndroRat service.

**Comment by Irzamhac** [comment]
> For that, you need to decompile the other apk( using apktool) and edit its smalli code in order to trigger the AndroRat service.
bro how to do that I tried to compare it with metasploit payload but it didn't helped me out

**Comment by Irzamhac** [comment]
> For that, you need to decompile the other apk( using apktool) and edit its smalli code in order to trigger the AndroRat service.

bro how to do that I tried to compare it with metasploit payload but it didn't helped me out
