### ISSUE TITLE
please help me on this issue 

### ISSUE THREAD

**Issue by sankalppatki** [karma9874/AndroRAT#252]
python3 androRAT.py --build --ngrok -p 8000 -o testchip.apk
[INFO] Tunnel_IP: 3.138.45.170 PORT: 14417
[INFO] Generating APK
[INFO] Building APK |
javac: invalid flag: -jar
Usage: javac <options> <source files>
use -help for a list of possible options

[ERROR] Building Failed

**Comment by lahadiyani** [comment]
ngrok not supported
