### ISSUE TITLE
> python3 androRAT.py --build -i 0.0.0.0 -p 8080 -o hehe.apk [INFO] Generating APK [INFO] Building APK | [SUCCESS] Successfully apk built in /data/data/com.termux/files/home/AndroRAT/hehe.apk [INFO] Signing the apk [INFO] Signing Apk | could not execute zipalign Run with '--debug' parameter to get additional information.

### ISSUE THREAD

**Issue by Razzak12345** [karma9874/AndroRAT#255]
> python3 androRAT.py --build -i 0.0.0.0 -p 8080 -o hehe.apk [INFO] Generating APK [INFO] Building APK | [SUCCESS] Successfully apk built in /data/data/com.termux/files/home/AndroRAT/hehe.apk [INFO] Signing the apk [INFO] Signing Apk | could not execute zipalign Run with '--debug' parameter to get additional information.
> 
> [ERROR] Signing Failed
> 
> I used android 11
did you find any solution?

_Originally posted by @Louioui in https://github.com/karma9874/AndroRAT/issues/186#issuecomment-1140292732_

**Comment by lahadiyani** [comment]
pkg install aapt
