### ISSUE TITLE
Apk does not signed succesfully

Please help 

### ISSUE THREAD

**Issue by evilforgit** [karma9874/AndroRAT#267]
Hello

It has many errors 

1. apk does not show in storage 

2. apk does not signed succesfully

And alike

**Comment by Anonymous1503** [comment]
So if you're using termux then do

pkg install aapt (not apt AAPT) 

or if you r a linux user do apt-get zipalign

Problem solved  💪😄👌

**Comment by IXSENPA1XI** [comment]
still dosent work
ive tryed everything and im getting nowhere fast
