### ISSUE TITLE
androRAT.py: error: unrecognized arguments: --bulid

### ISSUE THREAD

**Issue by AksharPandey19** [karma9874/AndroRAT#270]
androRAT.py: error: unrecognized arguments: --bulid command python3 androRAT.py --bulid -i Local_ip_adress -o hacker.apk

**Comment by SageTTs** [comment]
I have a small problem after running androRAT --build error message pops up saying 
[Error] Java not installed or found 
How can I deal with this I know I'll have to add Java just need help adding Java 
P.S I am running this on ish shell

**Comment by glare786** [comment]
`git clone https://github.com/h4ck3r0/Java-termux
