### ISSUE TITLE
OSError: [Errno 98] Address already in use plz help me

### ISSUE THREAD

**Issue by TRXxTigeR** [karma9874/AndroRAT#271]

**Comment by lucky7177** [comment]
for those wondering 
Kill process and start again


FIND PID (process id)
┌──(root㉿kali)-[/bin]
└─# `ps -h`
    824 tty7     Ssl+   4:04 /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch

   **11864** pts/1    S+     0:00 python3 androRAT.py --shell -i 0.0.0.0 -p 4444
                          
KILL PID   THE PID (yours will be diffrent !!)                                                                                                                                                                 
┌──(root㉿kali)-[/bin]
└─# `kill -9 `11864 

START AGAIN

                                                                                                                                                                                                   
┌──(root㉿kali)-[/home/k/AndroRAT]
└─# `python3 androRAT.py --shell -i 0.0.0.0 -p 4444`


                    _           _____         _______                                                                                                                                              
    /\             | |         |  __ \     /\|__   __|                                                                                                                                             
   /  \   _ __   __| |_ __ ___ | |__) |   /  \  | |                                                                                                                                                
  / /\ \ | '_ \ / _` | '__/ _ \|  _  /   / /\ \ | |                                                                                                                                                
 / ____ \| | | | (_| | | | (_) | | \ \  / ____ \| |                                                                                                                                                
/_/    \_\_| |_|\__,_|_|  \___/|_|  \_\/_/    \_\_|                                                                                                                                                
                                                                                                                                                                                                   
                                       - By karma9874                                                                                                                                              
                                                                                                                                                                                                   
[INFO] Waiting for Connections
