### ISSUE TITLE
Doesn't detect java on device 

### ISSUE THREAD

**Issue by Dan451yt** [karma9874/AndroRAT#272]
I'm using termux and doesn't detect java ik it works on termux I saw someone else using it and I have java

**Comment by Anonymous1503** [comment]
pkg install java

**Comment by Dan451yt** [comment]
Can't find java error when I do that or something

**Comment by Anonymous1503** [comment]
Send ss?

**Comment by SageTTs** [comment]
I'm having the same issue on ish shell can you please walk me through adding Java
