### ISSUE TITLE
im getting a java error 

### ISSUE THREAD

**Issue by Anonymous1503** [karma9874/AndroRAT#273]
![IMG_20230604_101933](https://github.com/karma9874/AndroRAT/assets/135541280/b8b88624-dced-4490-b82b-d68c6603a09c)
Getting a JAVA error
Am I supposed to install a package?

**Comment by Anonymous1503** [comment]
@karma9874 help pls sir

**Comment by ruslan6677** [comment]
yes i am getting the same error

**Comment by qcoderx** [comment]
install java on your devices

First, run the 
sudo apt update
 command

then run
sudo apt install default-jdk, if you want to run java apps frequently on your device or you are a software developer and you have enough storage to do so

OR
sudo apt install default-jre

if you just intend to run androRAT alone and you are not really a software developer
🙂🙂🙂

**Comment by Mursaleen00** [comment]
~/AndroRAT $ proot java -version                           java version "1.8.0_152"

~/AndroRAT $ python3 androRAT.py --build -i xxx -p 8282 -o test.apk
[ERROR] Java not installed or found



Can anyone guide me how to fix it

**Comment by Nwng70** [comment]
~/AndroRAT $ python3 androRAT.py --build -i 192.345 231.78 -p 3737 -p black.apk                            [ERROR] Java not installed or found

Please help me and with your kind heat
