### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by Anonymous1503** [karma9874/AndroRAT#274]
![IMG_20230604_130302](https://github.com/karma9874/AndroRAT/assets/135541280/359fcfce-885e-4ea9-aac6-2a95d0acac79)
![IMG_20230604_130321](https://github.com/karma9874/AndroRAT/assets/135541280/e5e756a2-b50c-49f2-bef3-333b7d2c5547)
So basically I'm trying to copy the file to web application server directory but it's giving me this error

Btw I'm not rooted cuz idk how to root my phone
@karma9874

**Comment by Anas68755** [comment]
Try fakeroot

**Comment by Anonymous1503** [comment]
you can't fake root a phone

**Comment by Anas68755** [comment]
@Anonymous1503 try fakeroot in termux
