### ISSUE TITLE
It Works fuc***g perfect!! But i have one question... 

### ISSUE THREAD

**Issue by m4dn35** [karma9874/AndroRAT#275]
If I close the terminal from which I am listening, how can I then reconnect to continue executing commands?

**Comment by BiskottoScriptato** [comment]
i wanna know that too

**Comment by IXSENPA1XI** [comment]
> If I close the terminal from which I am listening, how can I then reconnect to continue executing commands?

howd you get the damn thing to work dude
ive been trying to fix the damn thing not sighning for a good 2 hours now

**Comment by Gourav8078** [comment]
> > If I close the terminal from which I am listening, how can I then reconnect to continue executing commands?
> 
> howd you get the damn thing to work dude
> ive been trying to fix the damn thing not sighning for a good 2 hours now

Found anything?
