### ISSUE TITLE
Unable to reconnect

### ISSUE THREAD

**Issue by STANISLAVREVA** [karma9874/AndroRAT#283]
![Screenshot_20230712-000710](https://github.com/karma9874/AndroRAT/assets/137834382/6ebc3a74-4824-44ac-b165-3c1b688ce5c0)

I recently connected to an Android device but later lost my connection.  I don't know how to reconnect to my former connection. Must I send another APK file before I get connected?

**Comment by naveenpal4** [comment]
try sudo command to use androrat

**Comment by STANISLAVREVA** [comment]
I use Termux. Sudo does not work on it.  Can you explain to me in detail how to run the sudo command in order to reconnect to a device which I was recently connected to but lost my connection.

**Comment by helpteam118** [comment]
uninstall the apk and unistall back
