### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by erkankyn1** [karma9874/AndroRAT#29]
Hi, I use your program and I have an issue. I build an apk and my apk file name is system.apk. I installed this apk a Samsung device and it works only 2-3 minutes. When 2-3 minutes later I see this error and my connection is lost. 

android@shell:~$ cd ..
Traceback (most recent call last):
  File "androRAT.py", line 75, in <module>
    shell(conn)
  File "/root/RAT/utils.py", line 129, in shell
    msg = recvallShell(client)
  File "/root/RAT/utils.py", line 192, in recvallShell
    data = sock.recv(4096).decode("UTF-8","ignore")
ConnectionResetError: [Errno 104] Connection reset by peer

How can I figure this? 

Note: The device running and device have an internet connection.

**Comment by karma9874** [comment]
I m not sure about this but will check it soon 😅

**Comment by erkankyn1** [comment]
Hey, this problem is gone but I have a new one :D My victim phone (for education) is connected internet but Androrat is still checking connections. How can fix this?

**Comment by karma9874** [comment]
You did the port forwarding?

**Comment by erkankyn1** [comment]
Actually, I did all steps in the README file. Androrat worked 1 or 2 times but a few second later connection is gone.

**Comment by karma9874** [comment]
Which mobile model and android version are you using?

**Comment by erkankyn1** [comment]
Hwy, it's  SM-J710FQ
