### ISSUE TITLE
Error in androRAT.py

### ISSUE THREAD

**Issue by LinuxAnonymus** [karma9874/AndroRAT#296]
I am starting python3 server using following command in Kali Linux terminal to host created .apk file: 
```
sudo python3 androRAT.py --shell -i 0.0.0.0 -p 8000
```

When I am connecting to the server form android phone I get following message in terminal:
```
Got connection from ('192.x.x.x', 48852) -- IP address of android phone
 
GET /test.apk HTTP/1.1
Host: 192.x.x.x:8000 -- IP address of Linux machine.
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

Interpreter:/>
```

And on phone page is stuck on loading. 

After some time I am getting following error message:
```
Traceback (most recent call last):
  File "/home/Aldy/AndroRAT/androRAT.py", line 62, in <module>
    get_shell(args.ip,args.port) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aldy/AndroRAT/utils.py", line 342, in get_shell
    conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32] Broken pipe
```

Is there any solutions recommended to solve it?

**Comment by MuhammedEmirArtan** [comment]
Open the Port Forwarding on yoru modem's settings.

**Comment by LinuxAnonymus** [comment]
> Open the Port Forwarding on yoru modem's settings.

I'll try that right away, any guide I can follow ? 😅

**Comment by MuhammedEmirArtan** [comment]
What is the brand of your modem

**Comment by MuhammedEmirArtan** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.microcenter.com/tech_center/article/8323/how-to-forward-or-open-a-port-on-a-tenda-router&ved=2ahUKEwiDu7aUiJ6CAxXnQ_EDHTSgBUEQFnoECAwQBQ&usg=AOvVaw3kurj_auUSDspIuXPOCq6i

**Comment by MuhammedEmirArtan** [comment]
https://www.tendacn.com/in/faq/3273.html

**Comment by LinuxAnonymus** [comment]
> https://www.tendacn.com/in/faq/3273.html

Thanks, first I am trying without touching the modem or adapter. 

I am trying to achieve port forwarding using "localtunnel". 

Any suggestions with it ?

**Comment by MuhammedEmirArtan** [comment]
It's a bad idea. May not work

**Comment by syedikhlas0** [comment]
use portmapio instead guys ...
