### ISSUE TITLE
Problems on Miui 12

### ISSUE THREAD

**Issue by filirnd** [karma9874/AndroRAT#30]
Hi I try the RAT with Xiaomi mi 9t pro and Miui 12.0.1 global. The rat start without problems and interpeter is able to connect.
I setup no battery limitation and auto restart on App Info for the app. But if i reboot the device the app is not restart and there isn't way to restart becouse icon is hidden.

Any solution ?

**Comment by karma9874** [comment]
Auto restart of the app is still buggy will try to fix it soon and will provide an option for icon visibility in next update :)

**Comment by filirnd** [comment]
> Auto restart of the app is still buggy will try to fix it soon and will provide an option for icon visibility in next update :)

OK thank you!
