### ISSUE TITLE
python3 androRAT.py --shell -i 19×××××××× -p 80
[ERROR]  [Errno 13] Permission denied

### ISSUE THREAD

**Issue by zxmTEAM** [karma9874/AndroRAT#301]
BRO HOW TO SLOVE IT

**Comment by mohammadakram0705** [comment]
that is incorrect form
paste the following code in your pc
![Screenshot from 2023-12-03 20-28-27](https://github.com/karma9874/AndroRAT/assets/148874303/d1ca9a31-491b-41b6-b194-8a61a7918d84)

**Comment by mohammadakram0705** [comment]
paste this with out any changes

**Comment by mohammadakram0705** [comment]
paste this with out any changes

**Comment by mohammadakram0705** [comment]
**after you paste the code the output** 



![Screenshot from 2023-12-03 20-31-11](https://github.com/karma9874/AndroRAT/assets/148874303/012521c7-eacf-4adf-af8b-09b4314fc0e5)
