### ISSUE TITLE
AndroRat signing

### ISSUE THREAD

**Issue by DarkerLexus** [karma9874/AndroRAT#313]
When it is signing the apk, it shows that it's failing. Could you give me something to fix the issue. I use termux
![Screenshot_20240118_180716_Termux.jpg](https://github.com/karma9874/AndroRAT/assets/157037338/d7eb0fa6-f7df-442f-a441-aee7b4acb56d)

**Comment by Th3Oncel3r** [comment]
https://github.com/karma9874/AndroRAT/issues/186#issuecomment-1153133754
