### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by lawdefier** [karma9874/AndroRAT#320]
when i try to git clone this rep it says 
"
$ git clone https://github.com/karma9874/AndroRAT.git
Cloning into 'AndroRAT'...
remote: Enumerating objects: 5082, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (19/19), done.
error: 3909 bytes of body are still expectediB | 575.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
"

**Comment by lawdefier** [comment]
its solved i was trying to do it with git but had to do it with cmd

**Comment by Edward-hub17** [comment]
how did you solve it? because mine also has the same problem like yours.

**Comment by lawdefier** [comment]
Try doing the git clone process in the command prompt... Win + r (on
desktop) .... Type cmd and then git clone this repository.
