### ISSUE TITLE
git clone error. Please 🙏🥺 help me to install.

### ISSUE THREAD

**Issue by Eugenexjay** [karma9874/AndroRAT#326]
[1] I have cloned AndroRAT but there is an error.
![Screenshot_20240223-150940.png](https://github.com/karma9874/AndroRAT/assets/120492432/abe09c80-152a-4871-b4e6-6d181edfc69e)

I have also tried to download that ZIP File because when I "git clone" there is an error. But after I downloaded the ZIP File, the files in the ZIP file were missing. Please help me 🙏🙏
![Screenshot_20240223-151002.png](https://github.com/karma9874/AndroRAT/assets/120492432/1ed28362-8ac5-4ee0-9ef8-009abc4771fe)

![Screenshot_20240223-151120.png](https://github.com/karma9874/AndroRAT/assets/120492432/9e4defc4-2e9e-46b3-aafd-0a8bef418384)

Help me please to clone the tool. 🙏🙏🙏🥺

**Comment by plemyashkin01** [comment]
Try git clone depth=1 https://github.com/karma9874/AndroRAT.git
