### ISSUE TITLE
You need to update the androRAT for android 11/12/13. thanks for your contribution!

### ISSUE THREAD

**Issue by tomimk2** [karma9874/AndroRAT#330]

**Comment by Ethical1234567890** [comment]
Yes v13

**Comment by TheJet202** [comment]
I can't wait to see what the updates have

**Comment by Ethical1234567890** [comment]
Thank you so much I really appreciate you taking consern and administering
to my issue

**Comment by Batara777** [comment]
How

**Comment by Ethical1234567890** [comment]
Where and how do I update it on my Android 13

**Comment by Moulaye5839** [comment]
pls how to update AndroRAT ?

**Comment by risam4208-spec** [comment]
> pls how to update AndroRAT ?

just do git pull in that folder
