### ISSUE TITLE
The payload is not persistent

### ISSUE THREAD

**Issue by SilentCoderTM** [karma9874/AndroRAT#335]
The persistence of the payload stays for some minutes, but then it goes away and I can't re-establish the connection. I've tested on Android 10 and an older version of Android.

**Comment by Silentsniper1** [comment]
> The persistence of the payload stays for some minutes, but then it goes away and I can't re-establish the connection. I've tested on Android 10 and an older version of Android.

text me on discord my username is silentsniper0
