### ISSUE TITLE
never connecting when run on android phone

### ISSUE THREAD

**Issue by Zlaze** [karma9874/AndroRAT#340]
so when i run the andro rat on my phone, it doesnt connect on my pc i give it all permissions on my phone and stuff like that. andro rat should be installed correctly, what might be the problem? Need help:)

**Comment by vicious991** [comment]
are you running it on local network like connected to same wifi if it is and you did put ip address right it should work otherwise if you are work on Wan then you should have a static ip or DDNS

**Comment by kurohanaEN** [comment]
Same with me I'm using vmware for this and Memu player
And for some reason its doesn't work i do have it on bridge automatic tho

**Comment by herofahad777** [comment]
There are many reasons for not connecting if the receiver is in a different network and the sender is in a different network, then the problems can be 
1. Your ISP is blocking all incoming connections (My special problem)
2. Your firewall is not set and needs some ports to be open.
3. Do port forwarding
4. IDK, check google, use debugger like a print screen of what the app is doing when connecting and what is happening

**Comment by herofahad777** [comment]
> Same with me I'm using vmware for this and Memu player And for some reason its doesn't work i do have it on bridge automatic tho

Try it on a real phone

**Comment by herofahad777** [comment]
> so when i run the andro rat on my phone, it doesnt connect on my pc i give it all permissions on my phone and stuff like that. andro rat should be installed correctly, what might be the problem? Need help:)

My personal solution is to use tailscale or something similar if you are trying it from outside the  network
