### ISSUE TITLE
crached the phone 

### ISSUE THREAD

**Issue by mars0x1** [karma9874/AndroRAT#341]
it got hot and started flashing white on the scrreen

**Comment by Zlaze** [comment]
That doesnt sound good! what phone version do you use??

**Comment by mars0x1** [comment]
my android version is 8.0.0 and im using a hawawie nova 2 plus

**Comment by Zlaze** [comment]
> my android version is 8.0.0 and im using a hawawie nova 2 plus

i am not sure if thats too old might be how long have you had the phone? might be a battery issue :(

**Comment by mars0x1** [comment]
no not battery issue everything is fine

**Comment by Zlaze** [comment]
> no not battery issue everything is fine

Hmmm might be that there is something wrong with androrat? Maybe you have somehow gotten a op version if it that crashes a phone haha 😂 jokes aside there must be some kind off problem with the target phone might help if you contact huaweii or some dev of androrat
