### ISSUE TITLE
sysctl start apache2.service

### ISSUE THREAD

**Issue by UNKNOWN11278** [karma9874/AndroRAT#346]
After reinstalling the AndroRAT I am facing a problem that is related to this command 
**sysctl start apache2.service**
It started showing me error.
**sysctl: cannot stat /proc/sys/start: No such file or directory
sysctl: cannot stat /proc/sys/apache2/service: No such file or directory**
I hope it can be solved as soon as possible.

**Comment by Mashcracker17** [comment]
Oky
