### ISSUE TITLE
AWESOME TOOL! Needs to load upon reboot function

### ISSUE THREAD

**Issue by patrickruda** [karma9874/AndroRAT#35]
I just began testing this and works very well. I was hoping you might be able to introduce a feature where it will load upon restart and possibly a way to sign .apk whereas to avoid AV detection

**Comment by karma9874** [comment]
Auto restart is still buggy will try to fix it in the next version and the apk is already signed, is AV still detecting it as a virus?

**Comment by hackersploitaayush** [comment]
> Auto restart is still buggy will try to fix it in the next version and the apk is already signed, is AV still detecting it as a virus?

No , I tried it and AV is not detecting it.Your tool is really awesome.I have not seen a better tool than yours ;

**Comment by hackersploitaayush** [comment]
> @hackersploitaayush thank you so much :)

Bro i need one help tho when i try to open the shell it says cannot assign requested address(line 53 in module)error.How can i fix it?.I am using portmap.io amd in ip i enter the basic portmap ip which is 193.161.193.99
