### ISSUE TITLE
I cannot open the shell 

### ISSUE THREAD

**Issue by hackersploitaayush** [karma9874/AndroRAT#37]
It shows the following error when i try to open the shell 

Traceback (most recent call last):

  File "androRAT.py", line 53, in <module>

    soc.bind((ip, port))

OSError: [Errno 99] Cannot assign requested address

I am using java 8

**Comment by karma9874** [comment]
This error is often caused by a wrong IP address. You can use the command ifconfig to check whether your machine has this IP address.

**Comment by hackersploitaayush** [comment]
Bro i use portmap.io and i use basic portmap.io ip which is 193.161.193.99

**Comment by karma9874** [comment]
use the portmap.io ip to build the apk and for shell use 0.0.0.0

**Comment by hackersploitaayush** [comment]
> use the portmap.io ip to build the apk and for shell use 0.0.0.0 or 127.0.0.1
 Thx it worked but this app is not persistent tho.I am using android 8.0 + and it loses the connection within a few minutes

**Comment by karma9874** [comment]
I guess you need to allow the app to run in background from setting, most OS now mainly stop apps from running in background

**Comment by Maheshgaonkar62** [comment]
Same error me in RDP aws.  How to fix it

**Comment by sahillimba** [comment]
> 

bro port konsa use kerna hai portmap wala ya koi bhi build kerte time
