### ISSUE TITLE
why it is hanged on waiting for connection

### ISSUE THREAD

**Issue by roshisuthar** [karma9874/AndroRAT#38]
i have build apk in build mode installed that app in my android device now i m in shell mode but it is not getting connection from that android device.

**Comment by roshisuthar** [comment]
![Capture1](https://user-images.githubusercontent.com/43603697/97079172-63d29e00-160f-11eb-977c-229cb4ce5b96.PNG)

**Comment by roshisuthar** [comment]
Can anyone help me with this problem????

**Comment by karma9874** [comment]
Both the device are on the same network? or if this is over the internet then I suggest you to do port forwarding

**Comment by roshisuthar** [comment]
what is port forwarding can you be more specific???

**Comment by roshisuthar** [comment]
No both device are not on the same network ...

**Comment by karma9874** [comment]
Check for tutorials on ngrok or portmap.io

**Comment by alphaO4** [comment]
i have the same problem

**Comment by alphaO4** [comment]
both divices are on the same network, and even if not, port forwarding is activatet, as well as all firewalls being off line

**Comment by Tx-800** [comment]
i had created apk but not able to load download page from where we have to download mod apk

**Comment by sathish267** [comment]
> i have build apk in build mode installed that app in my android device now i m in shell mode but it is not getting connection from that android device.



> i have build apk in build mode installed that app in my android device now i m in shell mode but it is not getting connection from that android device

you got cleared your error  i have same issues help

**Comment by sathish267** [comment]
you got cleared your error i have same issues help
