### ISSUE TITLE
Unable to record audio

### ISSUE THREAD

**Issue by davidric** [karma9874/AndroRAT#39]
I tried all commands, all of them is working fine except the startAudio command. I got this error:
![image](https://user-images.githubusercontent.com/32319177/97571924-89e6ac80-1a1a-11eb-972c-2d1f1bcdd701.png)

**Comment by karma9874** [comment]
Well the text which you are seeing is base64 encoded so if you decode it you will get the audio file and that is what that script is supposed to do, but the text should not be visible, idk how you got that text though, can you tell me the steps so I can reproduce it 😅
