### ISSUE TITLE
AV Detected

### ISSUE THREAD

**Issue by patrickruda** [karma9874/AndroRAT#41]
I have uploaded this amazing tool on numerous different Android's and unfortunately the utility is detectable by all kinds of AV's. It was inevitable, however there must be a way to create new signatures to bypass AV's that can be regularly updated. Perhaps a binder that can be updated with new signatures to prevent the detection of the infected APK possibly? I am looking more and more into Metaploit's meterpreter's ways and TheFatRat, but as most things are nowadays too good to be true. TheFatRat has methods that are old and outdated. Metasploit still uses msfvenom which I am not certain is still updated with new AV bypasses ( last I checked msfvenom still was detectable ). If anyone knows a way to create a binder and a way to update undetectable signatures to each infected APK, let me know as that seems like the most promising concept I can think of.

**Comment by patrickruda** [comment]
Also, a botnet type APK style RAT would be ideal

**Comment by karma9874** [comment]
Hey, thanks for the suggestion, will try to overcome on this in next update :)
