### ISSUE TITLE
Cannot generate apk. 

### ISSUE THREAD

**Issue by CasparNuel** [karma9874/AndroRAT#48]
Upon building the APK file the following error occurs:
`No resource found that matches the given name: attr 'android:keyboardNavigationCluster'`

This is most likely related to the dependencies not being configured correctly in the gradle files.
Please look into this, I was unable to fix this problem myself even after updating all dependencies above `26.0.0`, I hope someone else is able to find the cause for this issue.

Thank you very much.

**Comment by karma9874** [comment]
Are u trying to manually build the apk?
