### ISSUE TITLE
huawei detects and removes app.

### ISSUE THREAD

**Issue by K4mey** [karma9874/AndroRAT#49]
Huawei phones can detect the app as a virus and remove it (i tested), i got it working on Huawei y6 2016 but the phone is constantly having an pop-up saying that the app is a virus and asking you to click the button to uninstall, however even if you don't uninstall the app, lot's of functions doesn't work.

**Comment by karma9874** [comment]
Yeah many anti-viruses now recognize AndroRAT as a virus 😅, will try to bypass it feature update
