### ISSUE TITLE
Building Failed

### ISSUE THREAD

**Issue by lordcharlx** [karma9874/AndroRAT#5]
![Screenshot at 2020-06-23 20-45-39](https://user-images.githubusercontent.com/5570136/85444503-e8d67980-b581-11ea-9826-f66551f4f18e.png)
quick fix

**Comment by karma9874** [comment]
Hey,
 I am unable to produce this error 
Can you provide the version of Java which you are using?

**Comment by anfaas1618** [comment]
> ![Screenshot at 2020-06-23 20-45-39](https://user-images.githubusercontent.com/5570136/85444503-e8d67980-b581-11ea-9826-f66551f4f18e.png)
> quick fix

use java version 8

**Comment by lordcharlx** [comment]
sorry for late response  im checking out now
