### ISSUE TITLE
Hey. Is there a possibility to make androRAT work when the pc and mobile are not connected in the same network.

### ISSUE THREAD

**Issue by greenhornhack** [karma9874/AndroRAT#51]
I want to secure my device and your androRAT works great but only when the mobile is in the same network as the pc. Is there any solution which could make it work? I read somewhere that if you want to have connection remotely you should use your public ip but this method doesn't work for me. Any help?

**Comment by karma9874** [comment]
Yeah, you can do port forwarding or simply use ngrok

**Comment by greenhornhack** [comment]
Wow thx, but could you do some kind of tutorial? Especially for androrat with ngrok? That would be very helpful . I'm trying it for few days and it still doesn't work for me :(

**Comment by karma9874** [comment]
will push ngrok support by  tomorrow
