### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by Arioshoma** [karma9874/AndroRAT#52]
Android 9
Unfortunately, the devices keep getting disconnected. Maybe that's a security feature from Android. How do you bypass it?
Maybe you can set the rat to execute itself after X seconds again? Or force the OS to keep the app open?

**Comment by karma9874** [comment]
You can enable the `Ignore battery optimization` from the settings which will force the OS to keep the app open

**Comment by swagkarna** [comment]
> Android 9
> Unfortunately, the devices keep getting disconnected. Maybe that's a security feature from Android. How do you bypass it?
> Maybe you can set the rat to execute itself after X seconds again? Or force the OS to keep the app open?

@karma9874 Use this Rat
