### ISSUE TITLE
[ERROR] error in initializing shell 

### ISSUE THREAD

**Issue by anfaas1618** [karma9874/AndroRAT#6]
Traceback (most recent call last):
  File "androRAT.py", line 53, in <module>
    soc.bind((ip, port))
OSError: [WinError 10049] The requested address is not valid in its context

////////////////////////////////////////////////////////////////////////////////////////

how to replicate this error 
1. go to noip get a static ip from thier 
2. put this ip to genrate apk using cmd 
3. then do this python androRAT.py --shell -i 47.247.176.204 -p 80
then you get this error

**Comment by karma9874** [comment]
Hey,
You're trying to bind to an external IP and your machine is not aware of this IP hence the error message. I would suggest trying that on the local machine with local IP or on the remote machine from where you are getting that IP and use `0.0.0.0`

**Comment by anfaas1618** [comment]
ok cool it works , but i coded my own java server from it thanks 
you can close this issue now.
