### ISSUE TITLE
'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by Rubelliumm** [karma9874/AndroRAT#60]
I cant figure out why I'm getting  this error.
I have compiled the apk using android studio and installed in my android .
and then I run the python server program,then I get this....can someone help me to solve this....???

```
Traceback (most recent call last):
  File "C:\Users\ahmed\Desktop\AndroRAT-master\androRAT.py", line 45, in <module>
    get_shell(args.ip,args.port)
  File "C:\Users\ahmed\Desktop\AndroRAT-master\utils.py", line 310, in get_shell
    while t.isAlive(): animate("Waiting for Connections  ")
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by karma9874** [comment]
Can I know the python version you are using?

**Comment by Rubelliumm** [comment]
> Can I know the python version you are using?

I'm using python 3.9.1

**Comment by karma9874** [comment]
So Thread 's method isAlive() was renamed to is_alive() since Python 3.9.0, so the temporary fix will be to use python version between `3.5 - 3.8`.

**Comment by bytesmalware** [comment]
Check you gmail Rubel

**Comment by bytesmalware** [comment]
Protonmail

**Comment by pl3bb0t** [comment]
Traceback (most recent call last):
  File "C:\Users\OWNER\Documents\GitHub\AndroRAT\androRAT.py", line 45, in <module>
    get_shell(args.ip,args.port)
  File "C:\Users\OWNER\Documents\GitHub\AndroRAT\utils.py", line 310, in get_shell
    while t.isAlive(): animate("Waiting for Connections  ")
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by karma9874** [comment]
@pl3bb0t https://github.com/karma9874/AndroRAT/issues/60#issuecomment-802643471
