### ISSUE TITLE
[Enhancement] Camera access when the phone is locked.

### ISSUE THREAD

**Issue by rayep** [karma9874/AndroRAT#65]
Hello There,

I've noticed a difference in display backlight behavior after installing the AndroRAT i.e., it keeps the backlight to low and up, so that the device will not get locked as the camera access would get interrupted/cannot be accessed when the phone is locked.

If that's the reason, then maybe I can suggest for a possible enhancement for that... I'm using the **Background Video Recorder - Quick VRec** for many years now, and it has the capability of recording the video using front or back cam continuously even we lock the mobile. _It would be so cool to have this feature incorporated in AndroRAT_ 😎😊

Play Store link - https://play.google.com/store/apps/details?id=com.kimcy929.secretvideorecorder&hl=en_IN&gl=US

Hope this might help!

Thanks!

**Comment by karma9874** [comment]
Hey,
Background Video Recorder - Quick VRec uses foreground service so when the recording is active you can see the notification which cannot be cleared.
But we can manually hide the notification for the desired app from the settings. so yeah, this might be a nice idea to implement.
If you have any idea for the code, PRs are welcomed :)
Thanks!

**Comment by rayep** [comment]
@karma9874 Thanks!

I wish I could be of more help, as I don't know coding 🙁 I'm pretty much useless on that part...!

**Comment by rayep** [comment]
@karma9874 is it possible to provide a version of AndroRAT which does not keep the display up all the time + latest modifications in place ?

I understand the implications that we can only execute commands only when the device is unlocked 😉

Thank you!

**Comment by yousifbakhit** [comment]
heiio

**Comment by yousifbakhit** [comment]
I Liked the aem boot in the free fier
