### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by sociallyakwardfrog** [karma9874/AndroRAT#66]
i am extremely new to this kinda stuff so i almoust have no idea what im doing, and i have installed all the requirements and installed python but when i try to double click the androrat file it wont open :/

**Comment by rayep** [comment]
@sociallyakwardfrog you need to open it from the CLI... Are you using linux or windows?

**Comment by rayep** [comment]
Command to open - python3 androRAT.py --build <arguments>
 
Refer to the Wiki page.

**Comment by bytesmalware** [comment]
Can I get some help rayep
