### ISSUE TITLE
Failed 

### ISSUE THREAD

**Issue by IbrahimovicAqram** [karma9874/AndroRAT#68]
Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

**Comment by bytesmalware** [comment]
> Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

![IMG-20210423-WA0003.jpg](https://user-images.githubusercontent.com/65878389/116177017-ba40a680-a730-11eb-8aa8-3eadb3e28e16.jpg)

**Comment by bytesmalware** [comment]
> Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

![IMG_20210427_081343.jpg](https://user-images.githubusercontent.com/65878389/116177064-ccbae000-a730-11eb-9a2d-4e0101874f24.jpg)

**Comment by bytesmalware** [comment]
![IMG_20210427_081343.jpg](https://user-images.githubusercontent.com/65878389/116177161-f1af5300-a730-11eb-9da3-d499efbd0b2c.jpg)

**Comment by karma9874** [comment]
Duplicate of #69
