### ISSUE TITLE
Unable to form apk using ngrok ,,, python version 3.6 ,, and all other requirements fulfilled 

### ISSUE THREAD

**Issue by bytesmalware** [karma9874/AndroRAT#70]
![IMG_20210428_104243.jpg](https://user-images.githubusercontent.com/65878389/116349915-ab302600-a80e-11eb-8524-cfeb98cfecde.jpg)

**Comment by bytesmalware** [comment]
Later I try chmod +x for  androRAT.py and utils.py ,,still not working

**Comment by karma9874** [comment]
First install the dependencies to do that type the following
```
pip install -r requirements.txt
```

**Comment by bytesmalware** [comment]
I install that too

**Comment by bytesmalware** [comment]
Let me tell you complete things ,,,firstly I use auto remove command to remove python 3.9 ,,than I install python 3.6.5 ,,,along with java JDK 8 ,,,,than I run that requirement.txt ,,,,,,,but no positive results

**Comment by bytesmalware** [comment]
See the image I attached,,,,and tell me ,, and one more thing ,,,pip colorama is latest one ,,,the version 19

**Comment by karma9874** [comment]
use pip3

**Comment by bytesmalware** [comment]
Failed

**Comment by bytesmalware** [comment]
Can I get your contact,,where I can talk you
