### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by bytesmalware** [karma9874/AndroRAT#74]
shell was successfully created ,,,I run several commands ,but when I run takepic 1 command  than Traceback ( most recent call last):  
File "androRAT.py" , line 46, in <module>
build (ip ,port,args.output, True,port_,icon)
File "/root/AndroRat/utils.py", line 392 , in build
  get_ shell("0.0.0.0" ,8000) if not ng else 
  get_shell("0.0.0.0" ,ng) 
File "/root/AndroRat/ utils.py" , line 339,in get_shell
conn.send(message_to_send.encode("UTF-8"))
BrokenPipeError: [Errno 32]  Broken pipe 

i run a command  device info ,I got the result but fail to execute next command ,I am adding error containing click along with apk generating and requirement click 
#
![IMG_20210510_092135](https://user-images.githubusercontent.com/65878389/117604344-cc7c0500-b172-11eb-9d30-2bc09038be87.jpg)

![IMG_20210510_091741](https://user-images.githubusercontent.com/65878389/117604304-b66e4480-b172-11eb-8491-d28f0a3e3f09.jpg)

**Comment by karma9874** [comment]
I have just updated some packages here can u do a fresh clone and try again?

**Comment by bytesmalware** [comment]
still same situation

**Comment by rayep** [comment]
@bytesmalware Is the phone gets locked while you get the BrokenPipe error? Did you exclude the RAT from battery optimizations?

**Comment by bytesmalware** [comment]
Broken pipe error , is still not fix , Trojan gonna shut down in Samsung
phones ,it's need to be get updated .
