### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Ahmed-Maher** [karma9874/AndroRAT#75]
after I execute this command it create the apk file but it give me this error.
![Capture](https://user-images.githubusercontent.com/81553688/117733290-9e89d580-b1f1-11eb-9689-408ddb31cdcc.PNG)

**Comment by karma9874** [comment]
@Ahmed-Maher  use java 8.

**Comment by karma9874** [comment]
Yes, give the extension apk to the file, `-o first.apk` and there is also typo in your IP I guess.

**Comment by Ahmed-Maher** [comment]
Yah it worked.
Thanks guys appreciate your help.
