### ISSUE TITLE
Hostname compatibility.

### ISSUE THREAD

**Issue by rayep** [karma9874/AndroRAT#76]
Hello @karma9874,

Just would like to confirm if hostname usage is okay instead of IP address while generating the RAT. Hence, it would be easy for me switch my command servers to different IP in the future.

It works without any issues when I use hostname now, is it expected to work?

**Comment by karma9874** [comment]
Yes, Socket Address can be pair of (IP address + port number) or (hostname + port number)

**Comment by rayep** [comment]
Perfect! 🤩 Thanks bro...
