### ISSUE TITLE
Feature request : Add ability to take screen capture / screenshot

### ISSUE THREAD

**Issue by snimavat** [karma9874/AndroRAT#77]
It would be great to have ability to do screen shot initially, and much better if we can record screen

**Comment by karma9874** [comment]
This will be not possible as the android OS restricts the usage of screenshot/record screen on an activity less app. As AndroRAT doesn't have any activity. But there's still might be some loopholes that can be used but I am not aware of any 😅.
Still will try to implement this if I found a way.

**Comment by ashidreza** [comment]
Hi karma9874, 
Its been march 2024. did you get any other way to have this screenshot capturing feature?
