### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AngelBlaizeC** [karma9874/AndroRAT#80]
i tried running shell but i get this error

![image](https://user-images.githubusercontent.com/78591190/119731286-52a18680-bea9-11eb-96c3-a25194ec0063.png)

**Comment by karma9874** [comment]
This error means that the remote side closed the connection, so this generally means that the android app is being force closed by the OS or maybe you are sending malformed data.
The probable solution will be to ignore the battery optimization settings on the app.
