### ISSUE TITLE
App Not Installed

### ISSUE THREAD

**Issue by FullPenetrationTesting** [karma9874/AndroRAT#81]
When i tried ro install payload apk in my device Android 11 and also tested in Android 8
![Screenshot_20210601-230216_Package_installer](https://user-images.githubusercontent.com/70372660/120366574-6fb4da00-c32d-11eb-8212-65fbb827c9ab.png)

It is showing app not installed 
How to fix this issue ?

**Comment by FullPenetrationTesting** [comment]
Api is limited below the Android 9
\_(-_-)_/

**Comment by omsurve** [comment]
use apk tool to dismantle and rebuild and sign or bind manually with a app

**Comment by FullPenetrationTesting** [comment]
Ahh it was signing issue..
Already fixed it :D

**Comment by madhavr-bio** [comment]
How did u fix it

**Comment by Malcolmxhive** [comment]
phone faile dto download adroRAT file fromweb  HELP????????
