### ISSUE TITLE
Error while building apk file: AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Faizudin205** [karma9874/AndroRAT#88]
Hello, id like to address the issue with the tool. When i want to build the apk file, I get an error message saying:

Traceback (most recent call last):
  File "androRAT.py", line 49, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "C:\Users\XBA5410\AndroRAT\utils.py", line 367, in b
    version_no = re.search(pattern, java_version.stderr).gr
AttributeError: 'NoneType' object has no attribute 'groups'

As shown in the screenshot below.

![image](https://user-images.githubusercontent.com/74866617/124435957-1a466f80-dda8-11eb-8596-18d41f6de794.png)

I have installed all of the requirements requested when i got this error.
I am currently using Python version 3.8.6

Can you fix the code?

**Comment by Th3J0nny** [comment]
You need to install Java. On Linux you can run `sudo apt-get install openjdk-8-jre`. 

Cause: In utils.py, line 366, the code will run `java -version`. If Java is not installed, this will return None.

**Comment by honeyfairy** [comment]
I am having this same issue
But java is installed, see below:

`┌──(root💀Gdrive)-[/home/honey/AndroRAT]
└─# python3 androRAT.py --build -i 145.45.45.9 -p 8090
Traceback (most recent call last):
  File "/home/honey/AndroRAT/androRAT.py", line 49, in <module>
    build(args.ip,port_,args.output,False,None,icon)
  File "/home/honey/AndroRAT/utils.py", line 367, in build
    version_no = re.search(pattern, java_version.stderr).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

┌──(root@Honeyd)-[/home/honey/AndroRAT]
└─# apt install openjdk-11-jre                                                                  1 ⨯
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openjdk-11-jre is already the newest version (11.0.12+7-2).
0 upgraded, 0 newly installed, 0 to remove and 694 not upgraded.

┌──(root@Honeyd)-[/home/honey/AndroRAT]
└─# apt install openjdk-17-jre
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openjdk-17-jre is already the newest version (17~35ea-1).
0 upgraded, 0 newly installed, 0 to remove and 694 not upgraded.

┌──(root@Honeyd)-[/home/honey/AndroRAT]
└─# java -version
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+35-Debian-1)
OpenJDK 64-Bit Server VM (build 17-ea+35-Debian-1, mixed mode, sharing)

┌──(root@Honeyd)-[/home/honey/AndroRAT]`

**Comment by karma9874** [comment]
```
export JAVA_HOME=path_to_java_8 home
```
You need to set the environment path to java 8
