### ISSUE TITLE
waiting for connection

### ISSUE THREAD

**Issue by ajay25641** [karma9874/AndroRAT#89]
after executing python androRAT.py --shell -i 0.0.0.0 -p 8000  , there is - [INFO] Waiting for Connections  / - for forever
![image](https://user-images.githubusercontent.com/65996214/126910163-e3285f71-c59e-4f5d-9976-f21f73b1f326.png)

**Comment by dpk01singh** [comment]
having the same issue any suggestions?

**Comment by yuuu7** [comment]
> آیا مشکل مشابهی دارید؟

Yes, I have the same problem. Thank you for your help

**Comment by yuuu7** [comment]
> آیا مشکل مشابهی دارید؟

Yes, I have the same problem. Thank you for your help

**Comment by benr961** [comment]
having the same issue right now, how can i resolve

**Comment by LIVESTREAMEROP** [comment]
same issue help me pls 

> after executing python androRAT.py --shell -i 0.0.0.0 -p 8000 , there is - [INFO] Waiting for Connections / - for forever ![image](https://user-images.githubusercontent.com/65996214/126910163-e3285f71-c59e-4f5d-9976-f21f73b1f326.png)
