### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by H420Prajyot** [karma9874/AndroRAT#9]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_4645150296992886629.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL1621721283628454375.tmp, -e, /tmp/APKTOOL7768992762503297111.tmp, -0, arsc, -I, /home/kali/.local/share/apktool/framework/1.apk, -S, /home/kali/AndroRAT/Compiled_apk_files/res, -M, /home/kali/AndroRAT/Compiled_apk_files/AndroidManifest.xml]

**Comment by karma9874** [comment]
Use java version 8

**Comment by H420Prajyot** [comment]
![Screenshot_2020-07-22-23-37-32.png](https://user-images.githubusercontent.com/60284945/88212174-ac8f4b00-cc0b-11ea-8b12-be46f16c595f.png)

But i am using java 8 than also error shows

**Comment by karma9874** [comment]
I think Kali Netunter is not suitable for this app. You should try this on standalone Windows or Linux OS

**Comment by H420Prajyot** [comment]
thank u @karma9874
