### ISSUE TITLE
 Non-ASCII character

### ISSUE THREAD

**Issue by xprimate** [karma9874/AndroRAT#92]
Error While running the command on ubuntu 20.0

`Traceback (most recent call last):
  File "androRAT.py", line 1, in <module>
    from utils import *
  File "/home/ogbonna/projects/AndroRAT/utils.py", line 42
SyntaxError: Non-ASCII character '\xe2' in file /home/user/projects/AndroRAT/utils.py on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`

Kindly help.

**Comment by eligarou** [comment]
j'ai le même probléme
