### ISSUE TITLE
ERROR !!

### ISSUE THREAD

**Issue by itsflu** [karma9874/AndroRAT#99]
python androRAT.py --shell -i 192.168.43.33 -p 8080
                                            
Traceback (most recent call last):
  File "androRAT.py", line 1, in <module>
    from utils import *
  File "/root/Documents/AndroRAT/utils.py", line 42
SyntaxError: Non-ASCII character '\xe2' in file /root/Documents/AndroRAT/utils.py on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details/

**Comment by yuuu7** [comment]
install library
